Repository polylang/polylang, pull requests merged in 2020-06, with the labels that each got.

#511 Fix Author URI header in main plugin file
  polylang.php
Labels: doc

#514 Add composer and stop referencing Polylang Pro
  .gitignore
  .travis.yml
  admin/admin-base.php
  admin/admin-classic-editor.php
  admin/admin-filters-term.php
  admin/admin.php
  composer.json
  composer.lock
  css/admin.css
  frontend/frontend.php
  include/base.php
  include/class-polylang.php
  include/language.php
  include/rest-request.php
  install/install.php
  install/upgrade.php
  js/block-editor.js
  js/classic-editor.js
  js/post.js
  modules/plugins/plugins-compat.php
  modules/wizard/wizard.php
  modules/wpml/wpml-compat.php
  phpcs.xml.dist
  polylang.php
  settings/settings.php
  settings/view-languages.php
  settings/view-tab-lang.php
  tests/phpunit/includes/testcase-trait.php
  tests/phpunit/tests/plugins/test-jetpack.php
  tests/phpunit/tests/plugins/test-wp-importer.php
  tests/phpunit/tests/test-admin-static-pages.php
  tests/phpunit/tests/test-canonical.php
  tests/phpunit/tests/test-choose-lang-content.php
  tests/phpunit/tests/test-choose-lang-domain.php
  tests/phpunit/tests/test-filters.php
  tests/phpunit/tests/test-hreflang.php
  tests/phpunit/tests/test-model.php
  tests/phpunit/tests/test-nav-menus.php
  tests/phpunit/tests/test-no-languages.php
  tests/phpunit/tests/test-query.php
  tests/phpunit/tests/test-search-form.php
  tests/phpunit/tests/test-static-pages.php
  tests/phpunit/tests/test-strings.php
  tests/phpunit/tests/test-switcher.php
  tests/phpunit/tests/test-widgets-calendar.php
  tests/phpunit/tests/test-widgets-filter.php
  tests/phpunit/tests/test-wpml-config.php
  tests/phpunit/tests/test-wpml.php
  tests/phpunit/tests/themes/test-twenty-fourteen.php
  tests/phpunit/tests/themes/test-twenty-seventeen.php
  uninstall.php
Labels: enhancement

#520 Move instantiation of CRUD classes to PLL_Base
  admin/admin.php
  frontend/frontend.php
  include/base.php
  include/rest-request.php
Labels: enhancement

#513 Add tests to detect the modification of WordPress functions
  frontend/frontend-filters-search.php
  include/widget-calendar.php
  tests/phpunit/tests/test-copied-functions.php
Labels: phpunit tests

#523 Override ACF styles introduced in its 5.9.0 version
  css/admin.css
  css/admin.min.css
Labels: compatibility

#512 Support wildcards in parent keys of the wpml-config.xml
  modules/wpml/wpml-config.php
  tests/phpunit/data/wpml-config.xml
  tests/phpunit/tests/test-wpml-config.php
Labels: WPML API, enhancement

#527 Decrease the number of queries on pages list
  admin/admin-filters-post.php
Labels: Performance

#530 Save one db query when the object id is < 0
  include/translated-object.php
Labels: Performance

#529 Move all integrations to their own directory.
  integrations/aqua-resizer/aqua-resizer.php
  integrations/aqua-resizer/load.php
  integrations/custom-field-template/cft.php
  integrations/custom-field-template/load.php
  integrations/duplicate-post/duplicate-post.php
  integrations/duplicate-post/load.php
  integrations/integrations.php
  integrations/no-category-base/load.php
  integrations/no-category-base/no-category-base.php
  integrations/wp-sweep/load.php
  integrations/wp-sweep/wp-sweep.php
  integrations/yarpp/load.php
  integrations/yarpp/yarpp.php
  tests/phpunit/tests/plugins/test-yarpp.php
Labels: enhancement
