Repository polylang/polylang, pull requests merged in 2020-09, with the labels that each got.

#553 Whitelist jQuery methods for VIP WPCS
  js/classic-editor.js
  js/nav-menu.js
  js/post.js
  js/term.js
  js/widgets.js
  modules/wizard/js/languages-step.js
  modules/wizard/wizard.php
Labels: enhancement

#569 Fix fatal in MU Domain Mapping integration
  integrations/domain-mapping/domain-mapping.php
Labels: bug

#563 Fix fatal error when no language is defined
  modules/site-health/load.php
Labels: bug

#564 Fixes the links and strings stored in the indexable table since Yoast SEO 14.0
  integrations/wpseo/wpseo.php
Labels: Yoast seo

#568 Remove common l10n js variable
  js/admin.js
  js/admin.min.js
  modules/wizard/wizard.php
  settings/settings.php
Labels: WP 5.5, bug

#570 Fix PHP notice in sitemap module
  modules/sitemaps/sitemaps.php
Labels: bug

#575 Replace @link annotation by @see one
  modules/site-health/admin-site-health.php
Labels: doc

#573 Design selectmenu fields as other fields in settings languages pages
  css/selectmenu.css
  css/selectmenu.min.css
  js/admin.js
  js/admin.min.js
Labels: UI

#552 Move sanitization filters for German and Danish to their own class
  admin/admin-filters.php
  admin/admin.php
  include/filters-sanitization.php
  tests/phpunit/tests/test-admin-filters.php
Labels: Pro, block editor, bug
