Repository polylang/polylang, pull requests merged in 2020-11, with the labels that each got.

#611 Fix sitemaps always redirected to the default language
  modules/sitemaps/multilingual-sitemaps-provider.php
  modules/sitemaps/sitemaps.php
  tests/phpunit/includes/testcase-trait.php
  tests/phpunit/tests/test-canonical.php
Labels: bug

#612 Cache get_objects_in_language
  include/translated-object.php
Labels: Performance

#619 Add navigation markup to the language switcher widget
  include/widget-languages.php
Labels: WP 5.5, accessibility, enhancement

#618 Externalize javascript for the language switcher widget form
  include/widget-languages.php
  js/widgets.js
Labels: enhancement

#615 term.js code modernization
  js/term.js
Labels: WP 5.6

#614 post.js code modernization
  js/post.js
Labels: WP 5.6

#616 Fix jQuery.fn.change() event shorthand is deprecated
  modules/share-slug/settings-share-slug.php
Labels: WP 5.6

#617 Fix jQuery.fn.change() event shorthand is deprecated
  settings/settings-browser.php
Labels: WP 5.6

#621 fix(admin-base): jQuery.parseJSON is deprecated :use JSON.parse
  admin/admin-base.php
Labels: WP 5.6

#625 Fix jQuery.fn.change() event shorthand is deprecated
  settings/settings-browser.php
Labels: WP 5.6

#622 Reverse dependency between flags and languages list
  js/admin.js
Labels: WP 5.6

#624 admin.js code modernization
  js/admin.js
Labels: WP 5.6

#628 Remove deprecated function in classic-editor.js
  js/classic-editor.js
Labels: WP 5.6

#609 Make jQuery UI 1.12.1 compatible and keep backward compatibility with jQuery UI 1.11.4
  css/selectmenu.css
  js/admin.js
Labels: WP 5.6, bug

#629 Remove jQuery deprecated functions calls in block-editor.js
  js/block-editor.js
Labels: WP 5.6

#631 Migrate jquery wizard languages-step.js
  modules/wizard/js/languages-step.js
Labels: WP 5.6

#630 Replace shorthands which trigger events
  js/admin.js
Labels: WP 5.6

#626 Don't attempt to modify rewrite rules when there is no language
  modules/sitemaps/sitemaps.php
Labels: bug

#623 WP Sweep: Avoid removing translated default terms and breaking languages
  integrations/wp-sweep/wp-sweep.php
Labels: compatibility

#632 Require WP 5.1
  .travis.yml
  include/functions.php
  install/install-base.php
  modules/wpml/wpml-legacy-api.php
  polylang.php
  readme.txt
  tests/phpunit/tests/test-admin-filters.php
Labels: enhancement

#613 A new way to handle options
  admin/admin-base.php
  admin/admin-strings.php
  frontend/frontend-filters.php
  include/base.php
  include/mo.php
  include/translate-option.php
  integrations/twenty-seventeen/twenty-seven-teen.php
  integrations/wpseo/wpseo.php
  modules/wpml/wpml-config.php
  tests/phpunit/tests/test-strings.php
  tests/phpunit/tests/test-translate-option.php
Labels: enhancement

#635 Add margin under input and textarea fields
  css/admin.css
  css/admin.min.css
Labels: UI

#636 Improve the documentation for the update process in PLL_Translate_Option
  include/translate-option.php
Labels: doc

#637 Reorganize strings translations metaboxes so that they are side by side
  css/admin.css
  css/admin.min.css
Labels: UI, enhancement

#638 Fix text direction field not populated when selecting a predefined language
  js/admin.js
  js/admin.min.js
Labels: bug

#634 Fix canonical tests and page for posts not redirected
  frontend/frontend-filters-links.php
  tests/phpunit/tests/test-canonical.php
Labels: bug, phpunit tests

#640 Deactivate Polylang as soon as possible
  include/class-polylang.php
  polylang.php
Labels: bug

#641 Fix a fatal error when the translation group is corrupted
  include/translated-object.php
Labels: bug

#643 Yoast SEO Homepage : set Meta Description instead of title
  integrations/wpseo/wpseo.php
Labels: Yoast seo, bug

#639 Make jQuery UI selectmenu widget styles consistent with WordPress ones
  css/selectmenu.css
  css/selectmenu.min.css
  js/admin.js
  js/admin.min.js
Labels: WP 5.3, enhancement

#642 Insert WordPress core dynamic blocks doesn't work anymore in WP 5.6
  js/block-editor.js
  js/block-editor.min.js
Labels: WP 5.6, bug

#644 Fix a fatal error when mixing multiple domains and plain permalinks
  modules/sitemaps/sitemaps.php
Labels: bug

#646 Fix get_canonical() in PLL_Canonical_UnitTestCase
  tests/phpunit/includes/testcase-canonical.php
Labels: phpunit tests

#645 Fix canonical redirect for paged page for posts
  frontend/frontend-filters-links.php
  tests/phpunit/tests/test-canonical.php
Labels: bug

#648 Correct regression introduced by PR #597 and #634
  frontend/frontend-filters-links.php
  tests/phpunit/tests/test-canonical.php
Labels: bug

#647 Add tests for default category
  tests/phpunit/tests/test-columns.php
Labels: phpunit tests

#649 Fix PHP notice undefined index wp_the_query
  frontend/choose-lang-content.php
Labels: bug

#651 Handle SameSite parameter for language cookie
  frontend/choose-lang.php
  include/cookie.php
  integrations/cache/cache-compat.php
Labels: bug
