Repository polylang/polylang, pull requests merged in 2020-07, with the labels that each got.

#525 Udpate the get_calendar() method with the changes introduced in WP 5.5
  include/widget-calendar.php
  tests/phpunit/tests/test-copied-functions.php
Labels: WP 5.5

#532 Prevent Polylang and Polylang Pro to be activated at the same time
  polylang.php
Labels: bug

#516 Displays flags instead of dashicons-yes icon in list tables
  admin/admin-filters-columns.php
  css/admin.css
  css/admin.min.css
  tests/phpunit/tests/test-ajax-columns.php
  tests/phpunit/tests/test-columns.php
Labels: UX, enhancement

#522 site-health
  admin/admin-static-pages.php
  modules/site-health/admin-site-health.php
  modules/site-health/load.php
Labels: enhancement

#537 Use custom flags on demand
  frontend/frontend-nav-menu.php
  include/language.php
  include/links-model.php
  include/model.php
  include/switcher.php
  modules/site-health/admin-site-health.php
  tests/phpunit/tests/test-custom-data.php
Labels: bug

#531 Add compatibility with sitemaps
  modules/sitemaps/load.php
  modules/sitemaps/multilingual-sitemaps-provider.php
  modules/sitemaps/sitemaps.php
Labels: WP 5.5, enhancement

#526 Switcher block
  include/switcher.php
Labels: enhancement

#539 Replace usage of checked attribute by property
  include/widget-languages.php
  js/nav-menu.js
  js/nav-menu.min.js
Labels: WP 5.5, bug

#538 Improve performance on the plugins list page
  install/t15s.php
Labels: Performance

#544 Re-minify all files
  css/admin.min.css
  js/block-editor.min.js
  js/classic-editor.min.js
  js/nav-menu.min.js
  js/post.min.js
  js/term.min.js
  js/user.min.js
  js/widgets.min.js
Labels: bug

#545 Replace filter wp_sitemaps_register_providers by wp_sitemaps_add_provider
  modules/sitemaps/sitemaps.php
Labels: WP 5.5

#546 Delete the transient when updating to 2.8
  install/upgrade.php
Labels: Pro

#543 Outputs secure cookie when using ssl
  integrations/cache/cache-compat.php
Labels: bug

#547 wp_list_filter doesn't act as array_filter
  frontend/choose-lang.php
Labels: WP 5.5

#548 Prevent creating 2 terms with the same name and same language
  admin/admin-filters-term.php
  include/model.php
  tests/phpunit/tests/test-admin-filters-term.php
Labels: bug

#550 Fix sticky posts appearing 2 times in WP 5.5
  frontend/frontend-filters.php
  tests/phpunit/tests/test-query.php
Labels: WP 5.5

#551 Fix home url in sitemaps for subdomains and multiple domains
  modules/sitemaps/sitemaps.php
  tests/phpunit/tests/test-sitemaps.php
Labels: bug
