Repository polylang/polylang, pull requests merged in 2020-12, with the labels that each got.

#654 Fix update of option translations registered with a wildcard
  include/translate-option.php
  tests/phpunit/tests/test-translate-option.php
Labels: bug

#659 Use PLL() API function instead of $this to reference Polylang instance
  integrations/cache/cache-compat.php
Labels: bug

#665 Translate title-search-wpseo option
  integrations/wpseo/wpseo.php
Labels: Yoast seo, bug

#666 fix-pll_the_language-doc
  include/api.php
Labels: doc

#668 Update test config to add PHP 8
  .gitignore
  .travis.yml
  composer.json
  composer.lock
  phpunit.xml
  tests/bin/install-plugins.sh
  tests/bin/install-wp-tests.sh
  tests/phpunit/includes/bootstrap.php
  tests/phpunit/includes/speed-trap-listener.php
Labels: phpunit tests

#660 Use PHPdoc style to document PLL_Language properties and remove useless ones
  include/language.php
Labels: enhancement

#657 Define abstract methods in PLL_Translated_Object
  include/translated-object.php
Labels: enhancement

#656 Define abstract methods in PLL_Links_Model
  include/links-model.php
Labels: enhancement

#669 Run PHPCS in CI without conditions
  .travis.yml
Labels: enhancement

#662 Link the post saving to the metabox refreshing
  js/block-editor.js
  js/block-editor.min.js
Labels: block editor, bug

#593 Webpackization webpack5
  .distignore
  .gitignore
  bin/build.sh
  bin/distribute.sh
  composer.json
  composer.lock
  css/admin.min.css
  css/selectmenu.min.css
  js/admin.min.js
  js/block-editor.min.js
  js/classic-editor.min.js
  js/nav-menu.min.js
  js/post.min.js
  js/term.min.js
  js/user.min.js
  js/widgets.min.js
  modules/wizard/css/wizard.min.css
  modules/wizard/js/languages-step.min.js
  package-lock.json
  package.json
  webpack.config.js
Labels: enhancement

#671 Cleanup: Remove the PLL_Pointer class
  include/pointer.php
Labels: enhancement

#673 Replace a property by a local variable
  include/translate-option.php
Labels: enhancement

#676 Fix missing property declaration and documentation
  admin/admin-block-editor.php
  admin/admin-notices.php
  frontend/frontend-static-pages.php
  include/crud-posts.php
  include/nav-menu.php
  include/query.php
  include/static-pages.php
  modules/sync/sync-tax.php
  modules/sync/sync.php
  modules/wizard/wizard.php
  settings/settings-url.php
Labels: enhancement

#670 Use PHPDoc to document the main Polylang object properties
  admin/admin-base.php
  admin/admin.php
  frontend/frontend.php
  include/rest-request.php
  settings/settings.php
Labels: doc

#680 Improve project build for internal use
  bin/build.sh
Labels: enhancement

#672 Modernize CI
  .travis.yml
Labels: enhancement

#682 Typo in PLL_Base
  include/base.php
Labels: bug

#674 Integrate files minification (build process) in the release distribution process
  bin/distribute.sh
Labels: enhancement

#683 Fix missing or useless isset
  admin/admin-filters-columns.php
  admin/admin-filters-term.php
  admin/admin-model.php
  include/translated-object.php
  modules/sitemaps/sitemaps.php
Labels: enhancement

#684 Fix some documentation errors and wrong default values
  admin/admin-model.php
  admin/admin-nav-menu.php
  admin/admin.php
  frontend/frontend-filters-links.php
  frontend/frontend-static-pages.php
  frontend/frontend.php
  include/api.php
  include/links-directory.php
  include/model.php
  include/switcher.php
  include/translate-option.php
  include/translated-object.php
  include/translated-post.php
  include/translated-term.php
  modules/wpml/wpml-legacy-api.php
  settings/settings-licenses.php
  settings/settings.php
Labels: coding standards, doc

#681 Add missing documentation for class properties
  admin/admin-classic-editor.php
  admin/admin-filters-columns.php
  admin/admin-filters-media.php
  admin/admin-filters-post-base.php
  admin/admin-filters-post.php
  admin/admin-filters-term.php
  admin/admin-static-pages.php
  admin/admin-strings.php
  frontend/choose-lang-url.php
  frontend/choose-lang.php
  frontend/frontend-auto-translate.php
  frontend/frontend-filters-search.php
  frontend/frontend-filters.php
  frontend/frontend-links.php
  frontend/frontend-nav-menu.php
  include/cache.php
  include/crud-terms.php
  include/filters-links.php
  include/filters.php
  include/license.php
  include/links-default.php
  include/links-directory.php
  include/links-permalinks.php
  include/links-subdomain.php
  include/links.php
  include/model.php
  include/olt-manager.php
  include/walker-dropdown.php
  include/walker-list.php
  install/install-base.php
  install/upgrade.php
  integrations/wp-importer/wp-import.php
  integrations/wp-offload-media/as3cf.php
  modules/sync/sync-metas.php
  modules/sync/sync-post-metas.php
  modules/wpml/wpml-api.php
  modules/wpml/wpml-compat.php
  modules/wpml/wpml-config.php
  phpcs.xml.dist
  settings/table-string.php
Labels: doc

#686 Remove useless "Instance of" in class property documentation
  admin/admin-base.php
  admin/admin-block-editor.php
  admin/admin-classic-editor.php
  admin/admin-filters-columns.php
  admin/admin-filters-media.php
  admin/admin-filters-post-base.php
  admin/admin-filters-term.php
  admin/admin-static-pages.php
  admin/admin.php
  frontend/choose-lang.php
  frontend/frontend-auto-translate.php
  frontend/frontend-static-pages.php
  frontend/frontend.php
  include/base.php
  include/crud-posts.php
  include/crud-terms.php
  include/filters-links.php
  include/filters.php
  include/links-model.php
  include/links.php
  include/nav-menu.php
  include/query.php
  include/rest-request.php
  include/static-pages.php
  include/translated-object.php
  include/walker-list.php
  modules/sync/sync-metas.php
  modules/sync/sync-tax.php
  modules/sync/sync.php
  modules/wpml/wpml-compat.php
  modules/wpml/wpml-config.php
  settings/settings-module.php
  settings/settings.php
Labels: doc

#688 Fix usage of sanitize_user()
  include/filters-sanitization.php
Labels: bug

#691 Fix Variable $tr_parent in isset() always exists and is not nullable.
  modules/sync/sync.php
Labels: bug

#693 Encrypt slack key
  .travis.yml
Labels: enhancement

#690 Clarify the code of `PLL_Language::get_flag_informations()`
  include/language.php
Labels: enhancement

#694 Add PHPStan to continuous integration
  .travis.yml
  composer.json
  composer.lock
  phpcs.xml.dist
  phpstan.neon.dist
  tests/phpstan/constants.php
Labels: enhancement

#695 Fix the visibility of PLL_Query properties
  include/query.php
Labels: bug

#696 Improve the doc of PLL_Admin_Model
  admin/admin-model.php
Labels: coding standards, doc

#697 Remove obsolete function and fix load_textdomain_mofile() doc
  include/olt-manager.php
Labels: doc, enhancement
