Repository polylang/polylang, pull requests merged in 2020-03, with the labels that each got.

#461 Fix test_edit_language failing "randomly"
  tests/phpunit/tests/test-settings.php
Labels: phpunit tests

#459 Add Vary: Accept-Language http header
  frontend/choose-lang.php
Labels: enhancement

#460 Twenty Seventeen: Translate header video Youtube url
  modules/plugins/plugins-compat.php
Labels: Default themes, enhancement

#463 WP 5.4: Fix admin_body_class test failing
  tests/phpunit/tests/test-admin-filters.php
Labels: WP 5.4, phpunit tests

#466 Work around a WP issue which localizes the plugins pages hooks
  admin/admin-base.php
Labels: bug

#468 Decrease the number of Travis jobs
  .travis.yml
Labels: phpunit tests

#472 Fix deactivate license not working in settings
  modules/wizard/wizard.php
Labels: bug

#471 Forbid access to wizard steps when no language is defined
  modules/wizard/view-wizard-step-home-page.php
  modules/wizard/wizard.php
Labels: enhancement, wizard

#476 Add $languages initialization wrongly removed
  modules/wizard/wizard.php
Labels: bug

#477 Enforce content step as next steps depend on it
  modules/wizard/view-wizard-step-home-page.php
  modules/wizard/wizard.php
Labels: enhancement, wizard

#474 Apply _wp_specialchars to the name when checking if a term exists
  include/model.php
  tests/phpunit/tests/test-model.php
Labels: bug

#478 Move dismissed notices from user metas to site options
  admin/admin-notices.php
  install/upgrade.php
  tests/phpunit/tests/test-admin-notices.php
  uninstall.php
Labels: enhancement, wizard

#479 Remove the wizard notice CSS file
  css/admin.css
  css/admin.min.css
  lingotek/lingotek.php
  modules/wizard/css/wizard-notice.css
  modules/wizard/css/wizard-notice.min.css
  modules/wizard/wizard.php
Labels: enhancement, wizard

#480 Test if postboxes variable is defined
  js/admin.js
  js/admin.min.js
Labels: bug, wizard

#481 Fix database error when the setup wizard is launched the first time
  modules/wizard/wizard.php
Labels: bug, wizard
