Repository polylang/polylang, pull requests merged in 2021-07, with the labels that each got.

#889 Add test to improve coverage for PLL_Admin_Default_Term
  tests/phpunit/tests/test-default-term.php
Labels: phpunit tests

#892 Consistent margin between flag and select for post and media
  css/src/admin.css
Labels: UI

#896 Fix radio button display for small screen
  css/src/admin.css
Labels: UI, bug

#895 Update Webpack stack
  package-lock.json
  package.json
Labels: dependencies

#894 Fix RTL display in admin sidebar for translations table title
  css/src/admin.css
Labels: UI, bug

#890 Add page for posts label correctly on bulk translate
  admin/admin-static-pages.php
Labels: bug

#897 Fix margin for labels in add language form
  css/src/admin.css
  settings/view-tab-lang.php
Labels: UI
