Repository polylang/polylang, pull requests merged in 2021-04, with the labels that each got.

#797 Move all js files contained in js/ folder to the js/src subfolder and CSS files from css/ to css/src
  .distignore
  css/src/admin.css
  css/src/dialog.css
  css/src/selectmenu.css
  js/src/admin.js
  js/src/block-editor.js
  js/src/classic-editor.js
  js/src/lib/confirmation-modal.js
  js/src/nav-menu.js
  js/src/post.js
  js/src/term.js
  js/src/user.js
  js/src/widgets.js
  webpack.config.js
Labels: enhancement

#807 Correctly update translations group when saving media language
  admin/admin-classic-editor.php
  admin/admin-filters-media.php
  admin/admin-filters-post.php
  admin/admin-filters-term.php
  include/translated-object.php
  include/translated-post.php
  tests/phpunit/tests/test-media.php
  tests/phpunit/tests/test-translated-post.php
Labels: bug

#819 Remove is-svg package dependency
  package-lock.json
Labels: dependencies

#773 Bump min WP version to 5.4 and remove useless checks in tests
  .travis.yml
  phpcs.xml.dist
  polylang.php
  tests/phpunit/includes/testcase-domain.php
  tests/phpunit/tests/plugins/test-jetpack.php
  tests/phpunit/tests/test-admin-static-pages.php
  tests/phpunit/tests/test-wpml.php
Labels: enhancement

#714 Translation's language should match object's language when saving translations group
  admin/admin-filters-post-base.php
  include/translated-object.php
  tests/phpunit/includes/bootstrap.php
  tests/phpunit/includes/testcase-translated-object.php
  tests/phpunit/tests/test-translated-post.php
  tests/phpunit/tests/test-translated-term.php
Labels: bug

#820 Add a new method to check the modification of function copied from WordPress
  tests/phpunit/includes/check-wp-functions-trait.php
Labels: phpunit tests

#822 Remove update_post_meta_cache() call in the pages list table
  admin/admin-filters-post.php
Labels: Performance

#735 Create default term class
  admin/admin-base.php
  admin/admin-default-term.php
  admin/admin-filters-columns.php
  admin/admin-filters-term.php
  admin/admin-model.php
  include/filters.php
  include/model.php
  tests/phpunit/includes/testcase-trait.php
  tests/phpunit/tests/test-admin-filters-post.php
  tests/phpunit/tests/test-admin-filters-term.php
  tests/phpunit/tests/test-columns.php
  tests/phpunit/tests/test-create-delete-languages.php
  tests/phpunit/tests/test-default-term.php
  tests/phpunit/tests/test-terms-list.php
Labels: enhancement

#824 Insert pll_ajax_backend parameter in a new empty object
  admin/admin-base.php
Labels: bug

#817 First readme.md to describe build process
  .distignore
  .github/assets/polylang-logo.svg
  readme.md
Labels: doc, enhancement

#810 Refactor method sidebars_widgets
  admin/admin.php
  frontend/frontend-filters-widgets.php
  frontend/frontend-filters.php
  frontend/frontend.php
  include/rest-request.php
  tests/phpunit/tests/test-widgets-filter.php
Labels: widget screen

#827 Require simplexml in site health if a wpml-config.xml is found
  modules/wpml/wpml-config.php
Labels: enhancement
