Repository polylang/polylang, pull requests merged in 2021-01, with the labels that each got.

#685 Stop test execution if language is invalid
  tests/phpunit/includes/testcase-trait.php
  tests/phpunit/tests/test-create-delete-languages.php
Labels: phpunit tests

#706 Refresh media libraries for posts
  js/classic-editor.js
Labels: enhancement

#707 Splits the PLL_Sitemaps class
  modules/sitemaps/abstract-sitemaps.php
  modules/sitemaps/load.php
  modules/sitemaps/sitemaps-domain.php
  modules/sitemaps/sitemaps.php
  tests/phpunit/tests/test-sitemaps.php
Labels: enhancement

#705 Add array keys in list to be properly displayed in doc.polylang.pro
  include/language.php
Labels: doc

#710 Fix usage of wp_localize_script()
  js/admin.js
  modules/wizard/wizard.php
  settings/settings.php
Labels: enhancement

#700 Improve the doc for the api.
  include/api.php
Labels: doc

#701 Fix warning for the declaration of wpSetUpBeforeClass( $factory )
  tests/phpunit/includes/testcase-domain.php
  tests/phpunit/includes/testcase-trait.php
  tests/phpunit/tests/plugins/test-duplicate-post.php
  tests/phpunit/tests/plugins/test-jetpack.php
  tests/phpunit/tests/test-admin-filters-post.php
  tests/phpunit/tests/test-admin-filters-term.php
  tests/phpunit/tests/test-admin-filters.php
  tests/phpunit/tests/test-admin-model.php
  tests/phpunit/tests/test-admin-static-pages.php
  tests/phpunit/tests/test-admin.php
  tests/phpunit/tests/test-ajax-columns.php
  tests/phpunit/tests/test-ajax-filters-post.php
  tests/phpunit/tests/test-ajax-filters-term.php
  tests/phpunit/tests/test-ajax-on-front.php
  tests/phpunit/tests/test-auto-translate.php
  tests/phpunit/tests/test-canonical.php
  tests/phpunit/tests/test-choose-lang-content.php
  tests/phpunit/tests/test-choose-lang-domain.php
  tests/phpunit/tests/test-choose-lang.php
  tests/phpunit/tests/test-columns.php
  tests/phpunit/tests/test-filters-links.php
  tests/phpunit/tests/test-filters.php
  tests/phpunit/tests/test-flags.php
  tests/phpunit/tests/test-hreflang.php
  tests/phpunit/tests/test-links-default.php
  tests/phpunit/tests/test-links-directory.php
  tests/phpunit/tests/test-media.php
  tests/phpunit/tests/test-model.php
  tests/phpunit/tests/test-nav-menus.php
  tests/phpunit/tests/test-query.php
  tests/phpunit/tests/test-search-form.php
  tests/phpunit/tests/test-settings.php
  tests/phpunit/tests/test-sitemaps.php
  tests/phpunit/tests/test-slugs.php
  tests/phpunit/tests/test-static-pages.php
  tests/phpunit/tests/test-strings.php
  tests/phpunit/tests/test-switcher.php
  tests/phpunit/tests/test-sync.php
  tests/phpunit/tests/test-terms-list.php
  tests/phpunit/tests/test-translate-option.php
  tests/phpunit/tests/test-translate-page-for-posts.php
  tests/phpunit/tests/test-translated-post.php
  tests/phpunit/tests/test-translated-term.php
  tests/phpunit/tests/test-widgets-calendar.php
  tests/phpunit/tests/test-widgets-filter.php
  tests/phpunit/tests/test-wpml-config.php
  tests/phpunit/tests/test-wpml.php
  tests/phpunit/tests/themes/test-twenty-fourteen.php
  tests/phpunit/tests/themes/test-twenty-seventeen.php
Labels: phpunit tests

#719 Add tests for canonical redirects of post and page feeds
  tests/phpunit/tests/test-canonical.php
Labels: phpunit tests

#718 Improve inline doc
  admin/admin-links.php
  include/license.php
  include/model.php
  include/translate-option.php
  include/translated-object.php
  include/translated-post.php
  include/translated-term.php
  modules/sync/sync-tax.php
Labels: doc

#715 Use the filter get_object_terms instead of wp_get_object_terms
  include/translated-term.php
Labels: enhancement

#720 Increase PHPStan checks to level 6
  admin/admin-base.php
  admin/admin-filters-term.php
  frontend/choose-lang-content.php
  frontend/frontend-filters.php
  include/filters.php
  include/mo.php
  include/model.php
  include/olt-manager.php
  include/translated-post.php
  include/walker-dropdown.php
  include/walker-list.php
  modules/sync/sync-tax.php
  phpstan.neon.dist
Labels: enhancement

#722 Improve the precision of the inline doc, mainly for arrays
  admin/admin-block-editor.php
  admin/admin-filters-columns.php
  admin/admin-filters-post-base.php
  admin/admin-filters-term.php
  admin/admin-filters.php
  admin/admin-notices.php
  admin/admin-static-pages.php
  admin/admin.php
  frontend/frontend-filters.php
  frontend/frontend-nav-menu.php
  include/crud-posts.php
  include/crud-terms.php
  include/filters.php
  include/links-directory.php
  include/links-domain.php
  include/links-model.php
  include/links-subdomain.php
  include/nav-menu.php
  include/olt-manager.php
  include/translated-object.php
  include/translated-post.php
  include/translated-term.php
  modules/site-health/admin-site-health.php
  modules/sitemaps/sitemaps.php
  modules/sync/admin-sync.php
  modules/sync/settings-sync.php
  modules/sync/sync-metas.php
  modules/sync/sync-post-metas.php
  modules/sync/sync-tax.php
  modules/sync/sync.php
  modules/wizard/wizard.php
  modules/wpml/wpml-config.php
  settings/settings-cpt.php
  settings/settings-module.php
  settings/table-languages.php
  settings/table-settings.php
  settings/table-string.php
Labels: doc

#723 Fix argument of an invalid type supplied for foreach
  admin/admin-filters-post.php
  admin/admin-filters-term.php
  admin/admin-model.php
  frontend/frontend-nav-menu.php
  include/class-polylang.php
  include/language.php
  include/translated-object.php
  install/upgrade.php
  modules/wpml/wpml-config.php
Labels: enhancement

#727 Improve inline doc
  admin/admin-base.php
  admin/admin-classic-editor.php
  admin/admin-filters-columns.php
  admin/admin-filters-media.php
  admin/admin-filters-post.php
  admin/admin-filters-term.php
  admin/admin-filters.php
  admin/admin-model.php
  admin/admin-static-pages.php
  frontend/choose-lang-content.php
  frontend/choose-lang.php
  frontend/frontend-auto-translate.php
  frontend/frontend-filters-links.php
  frontend/frontend-links.php
  frontend/frontend-nav-menu.php
  frontend/frontend-static-pages.php
  frontend/frontend.php
  include/filters-links.php
  include/links-abstract-domain.php
  include/links-default.php
  include/links-directory.php
  include/links-domain.php
  include/links-model.php
  include/links-permalinks.php
  include/links-subdomain.php
  include/mo.php
  include/nav-menu.php
  include/olt-manager.php
  include/query.php
  include/switcher.php
  include/walker-dropdown.php
  include/walker-list.php
  install/upgrade.php
  modules/site-health/admin-site-health.php
  modules/sitemaps/sitemaps.php
  modules/wizard/wizard.php
  modules/wpml/wpml-compat.php
  settings/table-languages.php
  settings/table-settings.php
Labels: doc, enhancement

#728 More precision for objects inline doc
  admin/admin-base.php
  admin/admin.php
  frontend/choose-lang-content.php
  frontend/choose-lang.php
  frontend/frontend-filters-links.php
  frontend/frontend.php
  include/base.php
  include/crud-posts.php
  include/links-abstract-domain.php
  include/links-directory.php
  include/links-model.php
  include/links-permalinks.php
  include/links-subdomain.php
  include/query.php
  include/translated-object.php
  include/translated-post.php
  include/translated-term.php
  integrations/custom-field-template/cft.php
  integrations/wpseo/wpseo.php
  phpstan.neon.dist
  settings/settings.php
  settings/view-tab-lang.php
Labels: doc

#725 Use correct handle for admin script in Wizard's languages step
  modules/wizard/wizard.php
Labels: bug

#730 Change constant for register scripts and stylesheets
  admin/admin-base.php
  admin/admin-nav-menu.php
  modules/wizard/wizard.php
  settings/settings.php
Labels: enhancement
