Repository polylang/polylang, pull requests merged in 2021-02, with the labels that each got.

#721 Protect against chained redirects.
  frontend/frontend-filters-links.php
Labels: enhancement

#579 remove the "title" markup
  include/language.php
  tests/phpunit/tests/test-flags.php
Labels: accessibility, bug

#737 Test widgets filter is not displayed for page builders
  tests/phpunit/tests/test-widgets-filter.php
Labels: WP 5.7, widget screen

#733 Hide license keys
  include/license.php
Labels: enhancement

#738 Fix wrong action url in search forms
  frontend/frontend-filters-search.php
  tests/phpunit/tests/test-search-form.php
Labels: bug, compatibility

#729 Fix property access errors reported by PHPStan
  admin/admin-classic-editor.php
  admin/admin-filters-columns.php
  admin/admin-filters-post.php
  admin/admin-filters-term.php
  admin/admin-links.php
  admin/admin-model.php
  admin/admin-nav-menu.php
  admin/admin-notices.php
  admin/admin-static-pages.php
  frontend/choose-lang-content.php
  frontend/frontend-auto-translate.php
  frontend/frontend-filters-links.php
  include/crud-posts.php
  include/filters.php
  include/language.php
  include/model.php
  include/query.php
  include/translated-object.php
  include/translated-post.php
  include/translated-term.php
  modules/sitemaps/multilingual-sitemaps-provider.php
  modules/sync/admin-sync.php
  modules/sync/sync-tax.php
  modules/sync/sync.php
  modules/wizard/wizard.php
  modules/wpml/wpml-api.php
  modules/wpml/wpml-legacy-api.php
Labels: enhancement

#736 Legacy widgets filters
  admin/admin-filters-widgets-options.php
  admin/admin-filters.php
  admin/admin.php
  include/filters-widgets-options.php
  include/rest-request.php
  tests/phpunit/tests/test-strings.php
  tests/phpunit/tests/test-widgets-filter.php
Labels: widget screen

#742 Refactor tests to stop using a static $polylang object
  tests/bin/install-plugins.sh
  tests/phpunit/includes/testcase-domain.php
  tests/phpunit/includes/testcase-trait.php
  tests/phpunit/tests/plugins/test-duplicate-post.php
  tests/phpunit/tests/plugins/test-jetpack.php
  tests/phpunit/tests/plugins/test-wp-importer.php
  tests/phpunit/tests/plugins/test-yarpp.php
  tests/phpunit/tests/test-admin-filters-post.php
  tests/phpunit/tests/test-admin-filters-term.php
  tests/phpunit/tests/test-admin-filters.php
  tests/phpunit/tests/test-admin-model.php
  tests/phpunit/tests/test-admin-notices.php
  tests/phpunit/tests/test-admin-static-pages.php
  tests/phpunit/tests/test-admin.php
  tests/phpunit/tests/test-ajax-columns.php
  tests/phpunit/tests/test-ajax-filters-post.php
  tests/phpunit/tests/test-ajax-filters-term.php
  tests/phpunit/tests/test-ajax-on-front.php
  tests/phpunit/tests/test-auto-translate.php
  tests/phpunit/tests/test-canonical.php
  tests/phpunit/tests/test-choose-lang-content.php
  tests/phpunit/tests/test-choose-lang-domain.php
  tests/phpunit/tests/test-choose-lang.php
  tests/phpunit/tests/test-columns.php
  tests/phpunit/tests/test-create-delete-languages.php
  tests/phpunit/tests/test-filters-links.php
  tests/phpunit/tests/test-filters.php
  tests/phpunit/tests/test-flags.php
  tests/phpunit/tests/test-hreflang.php
  tests/phpunit/tests/test-install.php
  tests/phpunit/tests/test-links-default.php
  tests/phpunit/tests/test-links-directory.php
  tests/phpunit/tests/test-links-domain.php
  tests/phpunit/tests/test-links-subdomain.php
  tests/phpunit/tests/test-media.php
  tests/phpunit/tests/test-model.php
  tests/phpunit/tests/test-nav-menus.php
  tests/phpunit/tests/test-no-languages.php
  tests/phpunit/tests/test-query.php
  tests/phpunit/tests/test-search-form.php
  tests/phpunit/tests/test-settings-browser.php
  tests/phpunit/tests/test-settings-cpt.php
  tests/phpunit/tests/test-settings.php
  tests/phpunit/tests/test-sitemaps.php
  tests/phpunit/tests/test-slugs.php
  tests/phpunit/tests/test-static-pages.php
  tests/phpunit/tests/test-strings.php
  tests/phpunit/tests/test-switcher.php
  tests/phpunit/tests/test-sync.php
  tests/phpunit/tests/test-terms-list.php
  tests/phpunit/tests/test-translate-option.php
  tests/phpunit/tests/test-translate-page-for-posts.php
  tests/phpunit/tests/test-translated-post.php
  tests/phpunit/tests/test-translated-term.php
  tests/phpunit/tests/test-widgets-calendar.php
  tests/phpunit/tests/test-widgets-filter.php
  tests/phpunit/tests/test-wpml-config.php
  tests/phpunit/tests/test-wpml.php
  tests/phpunit/tests/themes/test-twenty-fourteen.php
  tests/phpunit/tests/themes/test-twenty-seventeen.php
Labels: phpunit tests

#734 Don't filter a WP_Query if it already includes a language tax query
  include/query.php
  tests/phpunit/tests/test-filters.php
Labels: bug

#747 Correct body border in wizard to override WordPress install styles
  modules/wizard/css/wizard.css
Labels: WP 5.7, bug

#711 Browser preferred language update
  .travis.yml
  behat.yml
  composer.json
  composer.lock
  frontend/accept-language.php
  frontend/accept-languages-collection.php
  frontend/choose-lang.php
  tests/features/bootstrap/BrowserPreferredLanguageContext.php
  tests/features/browser-preferred-language.feature
  tests/phpunit/tests/test-accept-languages-collection.php
  tests/phpunit/tests/test-admin.php
  tests/phpunit/tests/test-choose-lang.php
Labels: behat tests, enhancement

#746 Add a dialog box to ask a confirmation about a language changing.
  admin/admin-base.php
  js/block-editor.js
  js/classic-editor.js
  js/lib/confirmation-modal.js
Labels: enhancement

#749 jQuery: replace deprecated shorthand functions and syntax
  js/classic-editor.js
  js/nav-menu.js
  js/post.js
  js/term.js
  js/user.js
Labels: jQuery update

#751 Add a CSS classes on jQuery UI selectmenu widget elements
  js/admin.js
Labels: enhancement

#752 Add a CSS class on jQuery UI dialog widget
  js/lib/confirmation-modal.js
Labels: enhancement

#753 Override jQuery UI selectmenu widget styles
  css/selectmenu.css
Labels: compatibility

#754 Cancel language change when we're closing the confirmation dialog box.
  js/lib/confirmation-modal.js
Labels: bug

#755 Add styles to override jQuery UI dialog widget styles of WooCommerce
  admin/admin-base.php
  css/dialog.css
Labels: bug

#759 Update configuration to use polylang-phpstan
  .travis.yml
  composer.json
  composer.lock
  phpstan.neon.dist
  tests/phpstan/constants.php
Labels: phpstan

#760 Update phpstan-wordpress to 0.7.3 and fix new reported errors
  composer.lock
  include/crud-posts.php
  modules/wizard/wizard.php
  phpstan.neon.dist
  settings/table-string.php
Labels: phpstan

#761 Yoast: fix post type archive title and metadesc not translated
  integrations/wpseo/wpseo.php
Labels: Yoast seo

#763 Fix site title not translated in email change confirmation email
  include/base.php
  tests/phpunit/tests/test-filters.php
Labels: bug

#764 Remove exif_read_data error
  tests/phpunit/data/image.jpg
Labels: WP 5.7, phpunit tests

#766 Fix undefined index 'pagenow'
  include/crud-terms.php
Labels: WP 5.7, bug

#767 Add a travis job to test the deve version of WP with PHP 5.6
  .travis.yml
Labels: phpunit tests

#768 Rewrite how to add polylang parameters in all admin ajax requests
  admin/admin-base.php
Labels: compatibility

#769 Fix switcher block not working in a post retrieved in REST API
  include/api.php
  include/switcher.php
Labels: REST API, bug
