Repository polylang/polylang, pull requests merged in 2021-05, with the labels that each got.

#833 Correct english sentence
  modules/wizard/view-wizard-step-media.php
Labels: enhancement

#835 Support session cookie with the pll_cookie_expiration filter
  include/cookie.php
  integrations/cache/cache-compat.php
Labels: enhancement

#831 Set curlang as current post language when cleaning the post cache
  integrations/cache/cache-compat.php
Labels: cache

#839 Update postcss release
  package-lock.json
  package.json
Labels: dependencies

#838 Fix legacy widget dropdown preview
  include/widget-languages.php
Labels: widget screen

#837 Avoid javascript errors when a plugin define its own editor for translated post types
  js/src/lib/confirmation-modal.js
  modules/wizard/js/languages-step.js
Labels: compatibility

#830 Prevent race condition when deleting images
  include/crud-posts.php
  phpstan.neon.dist
Labels: bug

#843 Remove the WPML compatibility settings module
  modules/wpml/load.php
  modules/wpml/settings-wpml.php
Labels: enhancement

#845 Remove references to Polylang Pro classes in settings of previewed modules
  modules/share-slug/load.php
  modules/share-slug/settings-preview-share-slug.php
  modules/share-slug/settings-share-slug.php
  modules/translate-slugs/load.php
  modules/translate-slugs/settings-preview-translate-slugs.php
  modules/translate-slugs/settings-translate-slugs.php
Labels: enhancement

#842 Adapt widgets script to work both with legacy widgets screen and block-based widgets screen
  admin/admin-base.php
  js/src/widgets.js
Labels: widget screen
