Repository polylang/polylang, pull requests merged in 2021-08, with the labels that each got.

#898 Add composer commands to launch all our tools the same way
  composer.json
  readme.md
Labels: enhancement, tools

#903 Update composer dependencies and ignore new PHPStan errors
  composer.lock
  modules/wpml/wpml-api.php
  phpstan.neon.dist
Labels: dependencies, phpstan

#901 Improve rss feed support with plain permalinks
  frontend/frontend-filters-links.php
  tests/phpunit/tests/test-canonical.php
Labels: enhancement

#872 Fixing multiple dropdown switchers rendering both for blocks and widget
  include/switcher.php
  include/walker-dropdown.php
Labels: bug

#881 Define a language in REST context
  include/rest-request.php
  tests/phpunit/tests/test-rest-request.php
Labels: enhancement, block editor, REST API

#887 FIx category feed not redirected when the language code is wrong
  frontend/frontend-filters-links.php
  tests/phpunit/tests/test-canonical.php
Labels: bug

#905 Allow to remove the cookie with the pll_cookie expiration filter
  include/cookie.php
  integrations/cache/cache-compat.php
Labels: enhancement

#902 Test canonical redirect of CPT feeds
  tests/phpunit/tests/test-canonical.php
Labels: phpunit tests
