Repository polylang/polylang, pull requests merged in 2021-11, with the labels that each got.

#934 Fix user description escaping
  admin/admin-filters.php
Labels: bug

#917 Remove duplicated code
  modules/sync/sync-metas.php
Labels: enhancement

#935 Fix fatal error in PHPunit tests
  tests/phpunit/tests/plugins/test-duplicate-post.php
Labels: phpunit tests

#922 Fix second parameter of get_object_taxonomies()
  admin/admin-filters-post.php
Labels: enhancement

#923 Improve some PHPDocs
  include/license.php
  include/olt-manager.php
  integrations/integrations.php
  modules/wpml/wpml-config.php
  settings/settings-module.php
  settings/table-languages.php
  settings/table-string.php
Labels: doc

#936 Change ajax-response id not to target default ajax-response HTML tag which is used by WordPress.
  js/src/post.js
  js/src/term.js
Labels: bug, WP 5.9
