Repository polylang/polylang, pull requests merged in 2021-06, with the labels that each got.

#850 Don't add language columns when editing a term
  admin/admin-filters-columns.php
  tests/phpunit/tests/test-ajax-columns.php
  tests/phpunit/tests/test-columns.php
Labels: bug

#840 Allow to query comments by multiple languages
  include/filters.php
  tests/phpunit/tests/test-filters.php
Labels: enhancement

#844 Improve settings descriptions and change default values
  install/install.php
  settings/settings-browser.php
  settings/settings-media.php
  settings/settings-url.php
  tests/phpunit/includes/testcase-trait.php
Labels: enhancement

#852 Update Composer dependencies
  admin/admin-nav-menu.php
  composer.lock
  include/filters.php
  settings/table-string.php
Labels: dependencies, enhancement

#853 Allow to have multiple language switchers in dropdown mode for nav menu
  frontend/frontend-nav-menu.php
  tests/phpunit/tests/test-nav-menus.php
Labels: bug

#856 Fix wp screen notice
  admin/admin-filters-columns.php
  tests/phpunit/tests/test-ajax-columns.php
  tests/phpunit/tests/test-columns.php
Labels: bug

#821 Change Admin menu Background Color
  admin/admin-base.php
  css/src/admin.css
Labels: enhancement

#854 Fix block editor preload path compatibility with WordPress 5.8
  admin/admin-block-editor.php
  admin/block-editor-filter-preload-paths.php
  phpstan.neon.dist
  tests/phpunit/tests/test-admin-block-editor-test.php
  tests/phpunit/tests/test-block-editor-preload-paths.php
Labels: WP 5.8, compatibility

#857 Fix Trying to get property 'term_taxonomy_id' of non-object
  include/filters.php
Labels: bug

#858 Fix passing null arguments to legacy preload paths filters
  admin/block-editor-filter-preload-paths.php
  phpstan.neon.dist
  tests/phpunit/tests/test-block-editor-preload-paths.php
Labels: WP 5.8, bug

#859 Fix PHP notice for legacy widget block type already registered
  tests/phpunit/includes/testcase-trait.php
Labels: WP 5.8, phpunit tests

#860 Let filter block_editor_rest_api_preload_paths unchanged when no post is provided
  admin/block-editor-filter-preload-paths.php
  tests/phpunit/tests/test-block-editor-preload-paths.php
Labels: WP 5.8, bug

#861 PHP Notice: Trying to get property 'post_type' of non-object
  admin/admin-block-editor.php
Labels: WP 5.8, bug, widget screen

#862 Fix test_register_filter_with_custom_priority()
  tests/phpunit/tests/test-block-editor-preload-paths.php
Labels: phpunit tests

#863 Fix widget related tests
  tests/phpunit/tests/test-strings.php
  tests/phpunit/tests/test-widgets-filter.php
Labels: WP 5.8, phpunit tests

#864 Revert "Fix PHP notice for legacy widget block already registered (#859)"
  tests/phpunit/includes/testcase-trait.php
Labels: WP 5.8, phpunit tests

#866 Fix normalize-url dependency
  package-lock.json
  package.json
Labels: dependencies

#869 Fix PHP notice when adding a CPT archive link to a menu
  include/nav-menu.php
Labels: bug

#841 enable post search box when create_post capability is disabled
  admin/view-translations-post.php
Labels: bug

#867 Fix switcher preview in widget screen
  include/switcher.php
  tests/phpunit/tests/test-switcher.php
Labels: WP 5.8, widget block editor

#875 Remove gutenberg widgets screen name
  admin/admin-base.php
  admin/admin-filters-widgets-options.php
Labels: WP 5.8, widget block editor

#876 Don't set curlang in clean_post_cache hook
  integrations/cache/cache-compat.php
Labels: bug, cache

#878 Add clean build folders before build process
  package-lock.json
  package.json
Labels: enhancement, webpack

#880 Update dependency
  package-lock.json
Labels: dependencies

#884 Use use_block_editor_for_post filter instead of rest_api_init
  modules/sync/admin-sync.php
  tests/phpunit/tests/test-sync.php
Labels: WP 5.8, block editor

#885 Delay the copy of terms and post metas
  modules/sync/admin-sync.php
Labels: WP 5.8, bug

#879 Validate the redirect links before redirecting on frontend
  frontend/choose-lang.php
  frontend/frontend-filters-links.php
Labels: enhancement

#888 Fix a typo in a PHPUnit test comment
  tests/phpunit/tests/test-accept-language.php
Labels: doc, phpunit tests

#886 FIx the default category displayed in the Categories
  admin/admin-default-term.php
  tests/phpunit/tests/test-default-term.php
Labels: bug
