Repository polylang/polylang, pull requests merged in 2021-03, with the labels that each got.

#770 Don't output the js cookie for embeds
  integrations/cache/cache-compat.php
Labels: bug, cache

#743 Remove unused filter for WP_Widget::display_callback()
  frontend/frontend-filters.php
Labels: doc, enhancement

#777 Fix selectmenu breaking changes
  css/selectmenu.css
Labels: bug

#784 Add missing script dependencies
  admin/admin-base.php
Labels: bug

#782 fix/781 ensure that method clear_cache exists before calling it
  integrations/wpseo/wpseo.php
Labels: Yoast seo

#780 Fix greedy regex which may match all search <form> attributes
  frontend/frontend-filters-search.php
  tests/phpunit/tests/test-search-form.php
Labels: bug

#786 Remove wp-media dependency which doesn't exist
  admin/admin-base.php
Labels: bug

#785 Filter attachments query with original arguments
  js/classic-editor.js
Labels: bug

#787 Fix custom flags not working
  include/language.php
  tests/phpunit/tests/test-create-delete-languages.php
Labels: bug

#788 Link translations to script files
  admin/admin-base.php
Labels: bug

#795 Put hreflangs higher in the head section
  frontend/frontend-filters-links.php
Labels: enhancement

#792 Change constant to enqueue scripts from
  admin/admin-base.php
  admin/admin-nav-menu.php
  modules/wizard/wizard.php
  polylang.php
  settings/settings.php
Labels: bug

#794 Yoast : fix cpt breadcrumb title when the option is empty
  integrations/wpseo/wpseo.php
Labels: Yoast seo

#791 Fix warning on frontend-filters-links.php
  frontend/frontend-filters-links.php
Labels: bug

#789 Yoast SEO: Fix sitemap.xml not redirected on secondary domains
  integrations/wpseo/wpseo.php
Labels: Yoast seo

#793 Do not build WP_Styles global instance before add_theme_support() is called
  frontend/choose-lang.php
  tests/phpunit/tests/test-choose-lang-content.php
Labels: bug

#796 Work around the removal of the wpml-config.xml in Yoast SEO Premium
  integrations/wpseo/wpseo.php
Labels: Yoast seo, enhancement

#803 Add Polylang parameters in ajax request datas sent in JSON string format
  admin/admin-base.php
Labels: bug, compatibility

#802 Fix confirmation modal with WooCommerce and WordPress < 5.6
  css/dialog.css
  js/lib/confirmation-modal.js
  phpcs.xml.dist
Labels: WooCommerce, bug

#799 Fix array_flip warning when a language is corrupted
  include/language.php
Labels: enhancement

#800 Attempt to repair corrupted languages
  admin/admin-model.php
Labels: enhancement

#778 Fix accept language parameter
  frontend/accept-language.php
  frontend/accept-languages-collection.php
  tests/phpunit/tests/test-accept-language.php
Labels: phpstan

#806 Remove @package on EDD updater
  install/plugin-updater.php
Labels: doc

#816 Update the test for copied functions
  frontend/frontend-filters-search.php
  tests/phpunit/tests/test-copied-functions.php
Labels: phpunit tests

#815 Update js packages
  package-lock.json
  package.json
Labels: dependencies
