Repository polylang/polylang, pull requests merged in 2022-03, with the labels that each got.

#989 Site health debug info labels are already escaped by WordPress
  modules/site-health/admin-site-health.php
Labels: Site Health

#990 Let's require WP 5.6
  .travis.yml
  phpcs.xml.dist
  polylang.php
  readme.md
  readme.txt
  tests/phpunit/tests/plugins/test-jetpack.php
  tests/phpunit/tests/test-admin-filters-term.php
Labels: enhancement

#991 Introduce new class PLL_Db_Tools
  include/db-tools.php
  tests/phpunit/tests/test-db-tools.php
Labels: enhancement

#992 Filter the home url in render_block_core_site_title()
  frontend/frontend-filters-links.php
Labels: WP 5.9

#993 Add previous lang data to the hook 'pll_update_language'
  admin/admin-model.php
Labels: enhancement

#994 Allow dealerdirect/phpcodesniffer-composer-installer as of Composer 2.2
  .travis.yml
  composer.json
Labels: tools
