Repository polylang/polylang, pull requests merged in 2022-09, with the labels that each got.

#1105 Fix parent of translated category removed when assigning an untranslated parent
  modules/sync/sync.php
  tests/phpunit/tests/test-sync.php
Labels: bug

#1108 Use npm update instead
  bin/build.sh
  bin/distribute.sh
Labels: enhancement, tools

#1110 The factory property is now deprecated
  tests/phpunit/includes/testcase-translated-object.php
  tests/phpunit/tests/plugins/test-duplicate-post.php
  tests/phpunit/tests/plugins/test-jetpack.php
  tests/phpunit/tests/test-admin-block-editor-test.php
  tests/phpunit/tests/test-admin-filters-post.php
  tests/phpunit/tests/test-admin-filters-term.php
  tests/phpunit/tests/test-admin-filters.php
  tests/phpunit/tests/test-admin-model.php
  tests/phpunit/tests/test-ajax-columns.php
  tests/phpunit/tests/test-ajax-filters-post.php
  tests/phpunit/tests/test-ajax-filters-term.php
  tests/phpunit/tests/test-auto-translate.php
  tests/phpunit/tests/test-canonical.php
  tests/phpunit/tests/test-choose-lang-content.php
  tests/phpunit/tests/test-choose-lang-domain.php
  tests/phpunit/tests/test-choose-lang.php
  tests/phpunit/tests/test-columns.php
  tests/phpunit/tests/test-default-term.php
  tests/phpunit/tests/test-filters-links.php
  tests/phpunit/tests/test-filters.php
  tests/phpunit/tests/test-hreflang.php
  tests/phpunit/tests/test-install.php
  tests/phpunit/tests/test-links-default.php
  tests/phpunit/tests/test-links-domain.php
  tests/phpunit/tests/test-media.php
  tests/phpunit/tests/test-model.php
  tests/phpunit/tests/test-multisite.php
  tests/phpunit/tests/test-nav-menus.php
  tests/phpunit/tests/test-parent-page.php
  tests/phpunit/tests/test-query.php
  tests/phpunit/tests/test-settings.php
  tests/phpunit/tests/test-sitemaps.php
  tests/phpunit/tests/test-slugs.php
  tests/phpunit/tests/test-static-pages.php
  tests/phpunit/tests/test-switcher.php
  tests/phpunit/tests/test-sync.php
  tests/phpunit/tests/test-terms-list.php
  tests/phpunit/tests/test-translated-post.php
  tests/phpunit/tests/test-translated-term.php
  tests/phpunit/tests/test-widgets-calendar.php
  tests/phpunit/tests/test-widgets-filter.php
  tests/phpunit/tests/test-wpml-config.php
  tests/phpunit/tests/test-wpml.php
  tests/phpunit/tests/themes/test-twenty-fourteen.php
Labels: phpunit tests, WP 6.1

#1106 Fix PHPStan errors.
  frontend/frontend-filters.php
  include/crud-posts.php
  include/links-subdomain.php
  include/model.php
  include/static-pages.php
  include/translated-object.php
  include/widget-languages.php
  install/upgrade.php
  modules/site-health/admin-site-health.php
  phpstan-baseline.neon
  settings/settings-url.php
Labels: phpstan

#1116 Names wizard page to avoid a fatal error with WooCommerce 6.9.x release
  modules/wizard/wizard.php
Labels: WooCommerce

#1113 Refactor term slugs defined with language
  admin/admin-filters-term.php
  include/crud-terms.php
  phpstan-baseline.neon
  tests/phpunit/tests/test-admin-filters-term.php
  tests/phpunit/tests/test-slugs.php
Labels: enhancement

#1124 Fix PHP warning when a filtered taxonomy has no query var
  include/model.php
Labels: bug

#1126 Don't report objects without languages when no language exist
  include/model.php
Labels: bug

#1128 Remove temporary fix in PHPUnit test for WP ticket 55575
  tests/phpunit/tests/test-columns.php
Labels: phpunit tests, WP 6.0

#1130 Improve doc (WPCS) for classes related to the links models
  include/links-abstract-domain.php
  include/links-default.php
  include/links-directory.php
  include/links-domain.php
  include/links-model.php
  include/links-permalinks.php
  include/links-subdomain.php
Labels: doc

#1131 Translate Yoast SEO metas
  integrations/wpseo/wpseo.php
Labels: Yoast seo

#1119 Fix error with custom taxonomies as array
  frontend/frontend-auto-translate.php
Labels: bug
