Repository polylang/polylang, pull requests merged in 2022-04, with the labels that each got.

#997 Fix create default term for first language
  admin/admin-base.php
Labels: bug

#1001 Fix parent page for parent unstranslatable post type
  include/crud-posts.php
  tests/phpunit/tests/test-parent-page.php
Labels: bug

#1008 Set accepted context in do_meta_boxes()
  settings/view-tab-strings.php
Labels: phpstan

#1007 Fix arrays comparisons in model's tests
  tests/phpunit/tests/test-model.php
Labels: bug, phpunit tests, WP 6.0

#1004 Prevent term_exists() to be filtered by language
  include/filters.php
Labels: bug, WP 6.0

#1005 Only sync metas of sync tax
  integrations/wpseo/wpseo.php
  modules/sync/sync-tax.php
Labels: bug, Yoast seo

#975 Remove redundant code present in parent class
  modules/sitemaps/sitemaps.php
Labels: enhancement

#966 PHP 8.1: Fix deprecated notice fired in set_url_scheme()
  include/class-polylang.php
  include/links-model.php
  tests/phpunit/includes/testcase-canonical.php
  tests/phpunit/includes/testcase-trait.php
  tests/phpunit/tests/test-admin-filters-post.php
  tests/phpunit/tests/test-admin-model.php
  tests/phpunit/tests/test-canonical.php
  tests/phpunit/tests/test-default-term.php
  tests/phpunit/tests/test-settings.php
  tests/phpunit/tests/test-static-pages.php
  tests/phpunit/tests/test-sync.php
  tests/phpunit/tests/test-translated-term.php
Labels: enhancement, phpunit tests

#1019 Fix array comparison in testcase-domain
  tests/phpunit/includes/testcase-domain.php
Labels: phpunit tests, WP 6.0

#1000 Translate the "posts page" in get_post_type_archive_link()
  admin/admin-static-pages.php
  frontend/frontend-static-pages.php
  include/filters-links.php
  include/static-pages.php
  tests/phpunit/tests/test-admin-static-pages.php
  tests/phpunit/tests/test-static-pages.php
Labels: enhancement

#1010 Fixes failing tests for the inline edit form
  tests/phpunit/tests/test-columns.php
Labels: phpunit tests, WP 6.0

#1020 Add a term group when creating languages in tests.
  tests/phpunit/includes/testcase-trait.php
Labels: phpunit tests, WP 6.0

#1017 Avoid redirection in secondary language for terms request in permalinks
  frontend/frontend-filters-links.php
Labels: bug

#1018 Disable language dropdown for default categories in quick edit form
  admin/admin-filters-columns.php
  tests/phpunit/tests/test-columns.php
  tests/phpunit/tests/test-default-term.php
Labels: bug, UI

#1016 Update szepeviktor / phpstan-wordpress
  admin/admin-base.php
  admin/admin-block-editor.php
  admin/admin-classic-editor.php
  admin/admin-default-term.php
  admin/admin-filters-columns.php
  admin/admin-filters-media.php
  admin/admin-filters-post-base.php
  admin/admin-filters-post.php
  admin/admin-filters-term.php
  admin/admin-static-pages.php
  admin/admin-strings.php
  admin/admin.php
  composer.json
  frontend/choose-lang.php
  frontend/frontend-auto-translate.php
  frontend/frontend-filters-links.php
  frontend/frontend-filters-search.php
  frontend/frontend-filters-widgets.php
  frontend/frontend-links.php
  frontend/frontend-nav-menu.php
  frontend/frontend-static-pages.php
  frontend/frontend.php
  include/base.php
  include/cache.php
  include/crud-posts.php
  include/crud-terms.php
  include/db-tools.php
  include/filters-links.php
  include/filters.php
  include/language.php
  include/license.php
  include/links-default.php
  include/links-directory.php
  include/links-domain.php
  include/links-model.php
  include/links-subdomain.php
  include/model.php
  include/olt-manager.php
  include/query.php
  include/static-pages.php
  include/switcher.php
  install/t15s.php
  integrations/integrations.php
  integrations/wp-offload-media/as3cf.php
  modules/site-health/admin-site-health.php
  modules/sync/sync-metas.php
  modules/wizard/wizard.php
  modules/wpml/wpml-api.php
  modules/wpml/wpml-compat.php
  modules/wpml/wpml-config.php
  phpstan.neon.dist
  settings/settings-browser.php
  settings/settings-module.php
  settings/settings-url.php
  settings/settings.php
  settings/table-string.php
Labels: phpstan

#1022 Use PHPStan at max level and generate a baseline to ignore errors
  phpstan-baseline.neon
  phpstan.neon.dist
Labels: phpstan

#999 Remove DOMNodeInserted depreciation
  js/src/post.js
  js/src/term.js
Labels: enhancement

#1002 Block editor not available for the page for posts
  admin/admin-static-pages.php
  tests/phpunit/tests/test-admin-static-pages.php
Labels: bug, block editor

#1029 PHPStan 1.6 + php 7.4
  .travis.yml
  phpstan-baseline.neon
Labels: phpstan

#1025 Added a method to check for languages
  include/class-polylang.php
  include/model.php
  phpstan-baseline.neon
Labels: bug

#1011 Clean useless JS and centralize function
  js/src/block-editor.js
  js/src/classic-editor.js
  js/src/lib/metabox-autocomplete.js
Labels: enhancement

#1030 Re set the ajax call for post_lang_choice changes
  js/src/block-editor.js
Labels: bug
