Repository polylang/polylang, pull requests merged in 2022-02, with the labels that each got.

#972 Improve compatibility of wpml_object_id
  modules/wpml/wpml-legacy-api.php
Labels: enhancement, WPML API

#981 Remove Extra dot
  include/license.php
Labels: bug

#969 Check if simplexml available
  modules/site-health/admin-site-health.php
  modules/wpml/wpml-config.php
Labels: Site Health

#980 Improve performance of the get_pages() filter
  include/filters.php
  include/translated-object.php
Labels: Performance

#984 Improve sanitization and validation for translated objects
  include/translated-object.php
  include/translated-post.php
  include/translated-term.php
  phpstan.neon.dist
  tests/phpunit/tests/test-admin-filters-term.php
Labels: enhancement

#987 Fix type error in array_keys()
  modules/sync/sync-post-metas.php
Labels: bug
