Repository polylang/polylang, pull requests merged in 2022-05, with the labels that each got.

#1035 Bring back the content editor
  admin/admin-static-pages.php
  phpstan-baseline.neon
  tests/phpunit/tests/test-admin-static-pages.php
  tests/phpunit/tests/test-static-pages.php
Labels: bug, validated

#1040 Update PHPStan Baseline since esc_sql() parsing has now dynamic return type
  phpstan-baseline.neon
Labels: phpstan

#1039 Fix dropdown selector
  include/walker-dropdown.php
  tests/phpunit/tests/test-switcher.php
Labels: bug, accessibility

#1034 Improve readme
  readme.txt
Labels: doc

#1042 Load strings translations accordingly to user locale when the password is retrieved
  include/base.php
  tests/phpunit/tests/test-email-strings.php
  tests/phpunit/tests/test-filters.php
Labels: enhancement

#1047 Fix language selector for product quick edit
  js/src/post.js
Labels: bug, UI

#1052 Temporarily require phpStan <1.7
  .travis.yml
  composer.json
Labels: phpstan
