Repository polylang/polylang, pull requests merged in 2022-10, with the labels that each got.

#1132 Rework auto-translation of term slugs list in WP_Query
  frontend/frontend-auto-translate.php
  tests/phpunit/tests/test-auto-translate.php
Labels: bug

#1125 Fix term slug modification during update
  include/crud-terms.php
  tests/phpunit/tests/test-admin-filters-term.php
Labels: bug

#1137 Display again default language icon in wizard
  css/src/admin.css
Labels: bug, wizard

#1134 Replace first parameter of WordPress get_terms() function passed as a string with an array
  admin/admin-filters-post.php
  admin/admin-filters-term.php
  admin/admin-model.php
  frontend/frontend-auto-translate.php
  frontend/frontend-links.php
  frontend/frontend-static-pages.php
  include/crud-posts.php
  include/model.php
  integrations/wp-importer/wp-import.php
  phpstan-baseline.neon
  phpstan.neon.dist
  tests/phpunit/tests/test-admin-filters-term.php
  tests/phpunit/tests/test-admin-model.php
  tests/phpunit/tests/test-auto-translate.php
  tests/phpunit/tests/test-filters.php
  tests/phpunit/tests/test-install.php
  tests/phpunit/tests/test-translated-term.php
  uninstall.php
Labels: enhancement, phpstan

#1127 Extract gutenberg-blocks tags from WPML config to be able to export and import strings to translate for blocks
  modules/wpml/wpml-config.php
  phpstan-baseline.neon
  tests/phpunit/data/wpml-config.xml
  tests/phpunit/tests/test-wpml-config.php
Labels: enhancement, WPML

#1138 Replace Menu and page title Strings Translations by Translations
  admin/admin-base.php
Labels: enhancement, UI, Import / Export module

#1133 Support custom fields in wpml-config.xml
  modules/wpml/wpml-config.php
  tests/phpunit/data/wpml-config.xml
  tests/phpunit/tests/test-wpml-config.php
Labels: enhancement, WPML

#1139 Fix term update with same slugs
  admin/admin-filters-term.php
  include/crud-terms.php
  tests/phpunit/tests/test-admin-filters-term.php
  tests/phpunit/tests/test-ajax-filters-term.php
  tests/phpunit/tests/test-slugs.php
Labels: bug

#1103 Fix posts without languages displayed in Yoast SEO sitemap
  integrations/wpseo/wpseo.php
Labels: Yoast seo

#1141 Use WP format for arrays doc
  admin/admin-model.php
  include/db-tools.php
  include/filters.php
  include/model.php
  include/translated-object.php
Labels: doc

#1129 Avoid calling PLL_Translated_Term::_prime_terms_cache() 2 times
  include/translated-term.php
Labels: enhancement

#1140 Add support for wpml-config.xml to MU plugins
  modules/wpml/wpml-config.php
  phpstan-baseline.neon
Labels: enhancement, WPML
