Repository polylang/polylang, pull requests merged in 2022-08, with the labels that each got.

#1080 Fix redirect when permalink structure has no trailing slash
  include/links-directory.php
  phpstan-baseline.neon
  tests/phpunit/tests/test-canonical.php
  tests/phpunit/tests/test-links-directory.php
Labels: bug

#1084 Remove 2 WPCS exclusions
  frontend/frontend-static-pages.php
  phpcs.xml.dist
Labels: coding standards

#1068 Handle OR operator in WP_Tax_Query
  frontend/choose-lang.php
  include/query.php
  phpstan-baseline.neon
  tests/phpunit/tests/test-query.php
Labels: bug

#1090 Revert "Handle OR operator in WP_Tax_Query"
  frontend/choose-lang.php
  include/query.php
  phpstan-baseline.neon
  tests/phpunit/tests/test-query.php
Labels: bug

#1093 Various improvements for assets tests
  tests/phpunit/includes/testcase-assets.php
  tests/phpunit/tests/test-admin-assets.php
  tests/phpunit/tests/test-admin.php
Labels: phpunit tests

#1094 Improve documentation for sanitize_int_id()
  include/translated-object.php
  modules/sync/sync-metas.php
Labels: enhancement

#1087 Fix admin scripts tests
  tests/phpunit/includes/bootstrap.php
  tests/phpunit/includes/testcase-assets.php
  tests/phpunit/tests/test-admin-assets.php
  tests/phpunit/tests/test-admin.php
Labels: phpunit tests

#1083 Fix admin render widget nav menu
  admin/admin-base.php
  frontend/frontend-nav-menu.php
  include/rest-request.php
  js/src/block-editor.js
  phpstan-baseline.neon
  tests/phpunit/tests/test-rest-request.php
  tests/phpunit/tests/test-widget-nav-menu.php
Labels: bug

#1091 Fix test for core string translations
  tests/phpunit/tests/test-strings.php
Labels: phpunit tests, WP 6.1

#1098 Set language in tax query correctly when OR relation is used
  frontend/choose-lang.php
  include/query.php
  phpstan-baseline.neon
  tests/phpunit/tests/test-query.php
Labels: bug

#1099 Free PHPStan version
  .travis.yml
  composer.json
  phpstan-baseline.neon
Labels: phpstan

#1100 Fix media translation setting has no effect
  include/model.php
  tests/phpunit/tests/test-model.php
Labels: bug
