Repository polylang/polylang, pull requests merged in 2022-11, with the labels that each got.

#1143 php 8.2 and dynamic properties
  frontend/frontend-links.php
  include/base.php
  include/language.php
  include/links.php
  integrations/integrations.php
  phpstan-baseline.neon
  settings/settings-url.php
  settings/table-string.php
  tests/phpunit/includes/testcase-ajax.php
  tests/phpunit/includes/testcase-canonical.php
  tests/phpunit/includes/testcase-trait.php
  tests/phpunit/includes/testcase.php
  tests/phpunit/includes/wp-screen-mock.php
  tests/phpunit/tests/test-admin-block-editor-test.php
  tests/phpunit/tests/test-admin.php
  tests/phpunit/tests/test-block-editor-preload-paths.php
  tests/phpunit/tests/test-canonical-domain.php
  tests/phpunit/tests/test-choose-lang-domain.php
  tests/phpunit/tests/test-choose-lang.php
  tests/phpunit/tests/test-email-strings.php
  tests/phpunit/tests/test-frontend.php
  tests/phpunit/tests/test-license.php
  tests/phpunit/tests/test-links-directory.php
  tests/phpunit/tests/test-slugs.php
  tests/phpunit/tests/test-static-pages.php
  tests/phpunit/tests/test-switcher.php
Labels: enhancement

#1123 Fix is_front_page() when a static front page is not translated
  frontend/choose-lang.php
  tests/phpunit/tests/test-static-pages.php
Labels: bug

#1148 Fix PHPStan errors.
  frontend/frontend-filters-search.php
Labels: phpstan

#1151 Fix PHPStan errors since szepeviktor/phpstan-wordpress new release
  frontend/choose-lang-url.php
  include/filters.php
  include/license.php
  include/links-directory.php
  modules/sync/sync-tax.php
  modules/wpml/wpml-api.php
  phpstan-baseline.neon
  phpstan.neon.dist
Labels: phpstan

#1154 Only store term_ids in taxonomy relationships cache
  include/translated-object.php
Labels: Performance, WP 6.0

#1155 Replace deprecated function mb_convert_encoding() in tests
  tests/phpunit/tests/test-admin-filters-post.php
  tests/phpunit/tests/test-admin-filters-term.php
  tests/phpunit/tests/test-default-term.php
  tests/phpunit/tests/test-nav-menus.php
  tests/phpunit/tests/test-settings.php
  tests/phpunit/tests/test-switcher.php
Labels: phpunit tests
