Repository polylang/polylang, pull requests merged in 2022-12, with the labels that each got.

#1111 Fix update options when two PLL_Translate_Option are instanciated
  include/translate-option.php
  phpstan-baseline.neon
  tests/phpunit/tests/test-translate-option.php
Labels: bug

#1159 Split PLL_Translated_Object into 2 abstract classes
  frontend/choose-lang-content.php
  include/translatable-object-with-types-interface.php
  include/translatable-object-with-types-trait.php
  include/translatable-object.php
  include/translated-object.php
  include/translated-post.php
  include/translated-term.php
  phpstan-baseline.neon
  phpstan.neon.dist
Labels: enhancement

#1161 API and types improvement
  frontend/frontend-auto-translate.php
  include/api.php
  modules/sync/sync-tax.php
  modules/sync/sync.php
  phpstan-baseline.neon
  tests/phpunit/tests/plugins/test-duplicate-post.php
  tests/phpunit/tests/test-create-delete-languages.php
  tests/phpunit/tests/test-translated-post.php
Labels: enhancement

#1158 Split of PLL_Language and PLL_MO
  include/language-factory.php
  include/language.php
  include/mo.php
  phpstan-baseline.neon
Labels: enhancement

#1160 Add a registry for PLL_Translatable_Object
  admin/admin-model.php
  include/model.php
  include/translatable-object.php
  include/translatable-objects.php
  include/translated-object.php
  include/translated-term.php
  modules/wizard/wizard.php
  settings/settings.php
Labels: enhancement

#1165 Remove useless PLL_Translatable_Object::update_language()
  admin/admin-classic-editor.php
  admin/admin-filters-media.php
  admin/admin-filters-post.php
  admin/admin-filters-term.php
  include/translatable-object.php
  include/translated-object.php
  tests/phpunit/tests/test-translated-post.php
Labels: enhancement

#1168 Fix renamed method and PHPCS in PLL_Language_Factory
  include/language-factory.php
  include/model.php
Labels: bug

#1174 Move is_translated_object_type() to the trait
  include/translatable-object-with-types-trait.php
  include/translated-term.php
Labels: enhancement

#1177 Delete the languages list cache on upgrade
  install/upgrade.php
Labels: enhancement

#1175 Simplify languages list creation
  include/language-factory.php
  include/model.php
Labels: enhancement

#1167 Get rid of deprecated PLL_Language properties.
  frontend/frontend-filters.php
  include/filters.php
  include/model.php
  include/query.php
  integrations/wp-importer/wp-import.php
  integrations/wp-sweep/wp-sweep.php
  settings/table-languages.php
  tests/phpunit/tests/test-install.php
Labels: enhancement

#1170 Fix PHPunit errors since language objects refactor.
  admin/admin-model.php
  include/api.php
  include/language-factory.php
  include/language.php
  include/translated-object.php
  tests/phpunit/tests/test-accept-languages-collection.php
  tests/phpunit/tests/test-admin-model.php
Labels: phpunit tests

#1180 Avoid creating PLL_Language object to get flags.
  include/language.php
  modules/wizard/view-wizard-step-languages.php
  settings/view-tab-lang.php
Labels: bug

#1171 Update get_calendar() to match WP 6.2 changes
  include/widget-calendar.php
  tests/phpunit/tests/test-copied-functions.php
Labels: WP 6.2

#1173 Fix PHPunit failures since language objects refactor.
  tests/phpunit/tests/test-create-delete-languages.php
  tests/phpunit/tests/test-media.php
Labels: phpunit tests

#1181 Fix API doc
  include/api.php
Labels: doc

#1184 Add PHP 8.2 to Travis config
  .travis.yml
Labels: phpunit tests
