Repository polylang/polylang, pull requests merged in 2022-06, with the labels that each got.

#1058 Force empty string translation to empty string
  include/api.php
  include/mo.php
  phpstan.neon.dist
  tests/phpunit/tests/test-strings.php
Labels: bug

#1060 Avoid conflict with 3rd party
  css/src/admin.css
Labels: compatibility

#1062 Make the Site Health report more human readable.
  modules/site-health/admin-site-health.php
Labels: enhancement, Site Health
