Repository polylang/polylang, pull requests merged in 2023-06, with the labels that each got.

#1268 Fix pages sorting with get_pages() in WP 6.3
  admin/admin-classic-editor.php
  include/filters.php
  tests/phpunit/tests/test-ajax-filters-post.php
Labels: WP 6.3

#1295 Assign static pages to `PLL_Language` even if no translation exist.
  include/static-pages.php
  tests/phpunit/tests/test-single-language.php
Labels: bug, validated

#1306 wp_list_filter() now uses strict comparison
  tests/phpunit/tests/test-wpml.php
Labels: phpunit tests, WP 6.3

#1305 Don't set $_column_headers in list tables
  settings/table-languages.php
  settings/table-settings.php
  settings/table-string.php
Labels: WP 6.3

#1300 New filter for `PLL_Language` URLs instead of `site_url()`.
  include/language-factory.php
  include/language.php
  include/links-abstract-domain.php
  include/links-model.php
  tests/phpunit/includes/bootstrap.php
  tests/phpunit/includes/links-trait.php
  tests/phpunit/includes/testcase-domain.php
  tests/phpunit/tests/test-links-default.php
  tests/phpunit/tests/test-links-directory.php
  tests/phpunit/tests/test-links-domain.php
  tests/phpunit/tests/test-links-multi-domains-to-one.php
  tests/phpunit/tests/test-links-subdomain.php
Labels: bug, validated

#1308 Add Kirghiz to the predefined list of languages
  settings/languages.php
Labels: enhancement

#1307 Revert "Don't set $_column_headers in list tables"
  settings/table-languages.php
  settings/table-settings.php
  settings/table-string.php
  tests/phpunit/tests/test-settings-list-tables.php
  tests/phpunit/tests/test-settings.php
Labels: bug

#1310 Fix PHP 8.2 deprecated notice in tests
  phpunit.xml
  tests/phpunit/tests/test-settings-list-tables.php
Labels: phpunit tests
