Repository polylang/polylang, pull requests merged in 2023-09, with the labels that each got.

#1340 Prevent Patchwork to print text during init
  tests/bin/install-wp-tests.sh
Labels: phpunit tests

#1337 Bump min WP version to 5.9
  .github/workflows/integration-and-unit-tests.yml
  include/olt-manager.php
  phpcs.xml.dist
  polylang.php
  readme.md
  readme.txt
  tests/phpunit/tests/plugins/test-duplicate-post.php
  tests/phpunit/tests/plugins/test-jetpack.php
  tests/phpunit/tests/plugins/test-wp-importer.php
  tests/phpunit/tests/test-email-strings.php
  tests/phpunit/tests/test-widget-nav-menu.php
  tests/phpunit/tests/themes/test-twenty-fourteen.php
  tests/phpunit/tests/themes/test-twenty-seventeen.php
Labels: enhancement

#1339 Replaces pre_get_posts by parse_query in PLL_Frontend_Auto_Translate
  frontend/frontend-auto-translate.php
Labels: enhancement

#1336 Assign terms in the correct language
  include/crud-posts.php
  include/model.php
  phpstan-baseline.neon
  tests/phpunit/tests/test-admin-filters-term.php
  tests/phpunit/tests/test-crud-posts.php
Labels: bug, validated

#1332 Javascript type is not required for HTML5
  admin/admin-base.php
  frontend/frontend-filters-search.php
  include/switcher.php
  integrations/cache/cache-compat.php
  modules/wizard/view-wizard-page.php
  settings/settings-browser.php
Labels: enhancement

#1342 Prevent an error when updating a translated option while the blog is switched
  include/translate-option.php
  phpstan-baseline.neon
  tests/phpunit/tests/test-multisite-option.php
Labels: bug, multisite

#1341 Filter preload paths only for translatable entities.
  admin/admin-block-editor.php
  include/filter-rest-routes.php
  js/src/block-editor.js
  js/src/lib/filter-path-middleware.js
  phpstan-baseline.neon
  tests/phpunit/includes/testcase-preload-paths.php
  tests/phpunit/tests/test-admin-block-editor-test.php
  tests/phpunit/tests/test-preload-paths.php
Labels: block editor

#1351 Assign default language to post or term when no language is sent or defined
  include/crud-posts.php
  include/crud-terms.php
  phpstan-baseline.neon
  tests/phpunit/tests/test-rest-request.php
Labels: bug, WP 6.3

#1346 Use pre-increment in PLL_Widget_Calendar
  include/widget-calendar.php
  tests/phpunit/tests/test-copied-functions.php
Labels: coding standards, WP 6.4

#1355 Unhook `print_emoji_styles()` in tests.
  tests/phpunit/includes/testcase-trait.php
Labels: phpunit tests, WP 6.4

#1345 Fix rewrite rules for WordPress 6.4.
  include/base.php
  include/functions.php
  include/links-directory.php
  include/links-model.php
  include/links-permalinks.php
  phpstan-baseline.neon
Labels: WP 6.4
