Repository polylang/polylang, pull requests merged in 2023-05, with the labels that each got.

#1270 Fix the lang extraction from URL
  include/links-default.php
  tests/phpunit/tests/test-links-default.php
Labels: bug

#1225 WordPress managers do not detect Polylang Pro update
  include/license.php
Labels: compatibility

#1276 Revert #1263
  readme.txt
  settings/settings.php
  settings/view-languages.php
Labels: bug

#1269 Fix 3.4 upgrade notice.
  install/upgrade.php
  tests/phpunit/tests/test-upgrade.php
Labels: bug

#1278 Fix PHPStan errors related to intval usage
  admin/admin-filters-term.php
  include/static-pages.php
Labels: phpstan

#1281 Cast wp_parse_url() return value to string
  frontend/choose-lang-url.php
  phpstan-baseline.neon
Labels: phpstan

#1284 Use PLL_Cache to cache translated options
  include/translate-option.php
  tests/phpunit/tests/test-multisite-option.php
Labels: bug

#1285 Override `set_language_home_urls()` for domains and subdomains
  include/links-abstract-domain.php
  include/links-model.php
  tests/phpunit/tests/test-links-domain.php
Labels: bug, validated

#1287 Fix PHPStan errors.
  phpstan-baseline.neon
  settings/table-languages.php
  settings/table-string.php
Labels: phpstan

#1288 Fix warning on term_props
  include/model.php
  tests/phpunit/tests/test-model.php
Labels: bug

#1289 Fix customizer switching from the static front page to the blog
  frontend/frontend-static-pages.php
  frontend/frontend.php
  include/base.php
Labels: bug, Customizer
