Repository polylang/polylang, pull requests merged in 2023-07, with the labels that each got.

#1280 Use `sanitize_locale_name()` when available
  include/functions.php
  modules/wizard/wizard.php
  phpcs.xml.dist
  settings/settings.php
  tests/phpunit/tests/test-copied-functions.php
Labels: enhancement

#1283 Fix potential deprecated notices related to trim, rtrim
  admin/admin-filters-term.php
  include/class-polylang.php
  phpstan-baseline.neon
Labels: phpstan

#1313 Fix errors since PHPStan 1.10.22.
  frontend/choose-lang-content.php
  frontend/choose-lang.php
  include/links-abstract-domain.php
  phpstan-baseline.neon
  phpstan.neon.dist
Labels: phpstan

#1319 [MS] Fix option creation on blog creation
  install/install-base.php
  tests/phpunit/tests/test-multisite.php
Labels: bug, multisite

#1311 Don't reset the"static front page" option on deletion of a home page translation
  include/static-pages.php
  tests/phpunit/tests/test-static-pages.php
Labels: bug

#1322 Allow to mock some constants in tests
  frontend/frontend-filters-links.php
  include/functions.php
  include/language.php
  include/model.php
  integrations/domain-mapping/domain-mapping.php
Labels: phpunit tests

#1312 Fix tags translation during post update.
  include/crud-posts.php
  tests/phpunit/includes/testcase.php
  tests/phpunit/tests/test-crud-posts.php
Labels: bug

#1325 Make testcase classes abstract and autoloaded
  composer.json
  tests/phpunit/includes/bootstrap.php
  tests/phpunit/includes/testcase-ajax.php
  tests/phpunit/includes/testcase-assets.php
  tests/phpunit/includes/testcase-canonical.php
  tests/phpunit/includes/testcase-domain.php
  tests/phpunit/includes/testcase-translated-object.php
  tests/phpunit/includes/testcase.php
Labels: enhancement, phpunit tests

#1321 Require PHP 7 or higher
  composer.json
  phpcs.xml.dist
  polylang.php
  readme.txt
Labels: enhancement, WP 6.3

#1323 Use of optional chaining operator to prevent javascript error when excerpt field doesn't exist
  js/src/block-editor.js
  phpcs.xml.dist
Labels: bug, validated

#1326 Add pll_admin_ajax_params filter
  admin/admin-base.php
Labels: enhancement
