Repository polylang/polylang, pull requests merged in 2023-01, with the labels that each got.

#1185 Fix has_languages return
  include/model.php
Labels: bug

#1188 Remove Lingotek ad
  modules/lingotek/image01.gif
  modules/lingotek/image02.png
  modules/lingotek/image03.png
  modules/lingotek/image04.png
  modules/lingotek/lingotek.php
  modules/lingotek/load.php
  phpstan-baseline.neon
  readme.txt
  tests/phpunit/tests/test-admin-notices.php
Labels: enhancement

#1186 Do not set current language on post update anymore.
  admin/admin-base.php
  phpstan-baseline.neon
  tests/phpunit/tests/test-admin-filters-post.php
  tests/phpunit/tests/test-admin-filters-term.php
Labels: bug

#1191 Add "active" language property.
  include/language-factory.php
  include/language.php
  tests/phpunit/tests/test-create-delete-languages.php
Labels: enhancement

#1178 Improve flag properties setting
  admin/admin-model.php
  include/language-factory.php
  include/language.php
  include/links-abstract-domain.php
  include/links-model.php
  include/model.php
  tests/phpunit/tests/test-links-domain.php
  tests/phpunit/tests/test-sitemaps.php
Labels: enhancement

#1196 Fix translate option performance
  include/mo.php
  include/translate-option.php
Labels: Performance

#1192 Prepare for locale fallbacks
  include/language-factory.php
  include/language.php
  install/upgrade.php
  tests/phpunit/tests/test-create-delete-languages.php
Labels: enhancement

#1190 Add a custom admin body class
  admin/admin-filters.php
  tests/phpunit/tests/test-admin-filters.php
Labels: enhancement

#1197 Fix term import
  integrations/wp-importer/wp-import.php
Labels: bug

#1193 Don't override 'active' language property on update
  admin/admin-model.php
Labels: bug

#1182 Adds an object type parameter to get_objects_with_no_lang()
  include/model.php
  include/translatable-object-with-types-trait.php
  include/translatable-object.php
  include/translated-post.php
  include/translated-term.php
Labels: bug

#1199 Fix languages list order.
  include/model.php
  include/translatable-object-with-types-trait.php
  tests/phpunit/tests/test-create-delete-languages.php
Labels: bug

#1176 Tools to add secondary language terms
  admin/admin-model.php
  include/model.php
  phpstan-baseline.neon
  tests/phpunit/tests/test-model.php
Labels: enhancement

#1195 Remove language home and search urls setters.
  admin/admin-model.php
  frontend/choose-lang.php
  frontend/frontend-filters-search.php
  frontend/frontend-static-pages.php
  include/language-factory.php
  include/language.php
  include/links-abstract-domain.php
  include/links-default.php
  include/links-directory.php
  include/links-domain.php
  include/links-model.php
  include/links-permalinks.php
  include/links-subdomain.php
  include/links.php
  include/model.php
  include/static-pages.php
  modules/site-health/admin-site-health.php
  tests/phpunit/tests/test-model.php
Labels: enhancement

#1201 Filter the language term description
  admin/admin-model.php
Labels: enhancement

#1203 Add a new property to use for cache key
  include/translatable-object.php
  include/translated-post.php
  include/translated-term.php
Labels: bug

#1205 Improvement following #1195
  include/language.php
  include/links-default.php
  include/links-permalinks.php
  include/model.php
Labels: enhancement

#1198 Manage static pages initialization
  admin/admin-base.php
  frontend/frontend.php
  include/base.php
  include/class-polylang.php
  include/language-factory.php
  include/language.php
  include/links-model.php
  include/rest-request.php
  include/static-pages.php
  include/translated-object.php
  modules/share-slug/load.php
  modules/site-health/load.php
  modules/sitemaps/load.php
  modules/sync/load.php
  modules/translate-slugs/load.php
  modules/wpml/load.php
  tests/phpunit/tests/test-static-pages.php
  tests/phpunit/tests/test-translate-page-for-posts.php
Labels: enhancement
