Repository polylang/polylang, pull requests merged in 2023-04, with the labels that each got.

#1246 Prevent "unknown propertiy" warnings
  include/olt-manager.php
Labels: bug

#1242 Ease creation of 3rd party language taxonomies
  include/class-polylang.php
  include/model.php
  phpstan-baseline.neon
  settings/settings.php
  tests/phpunit/data/translatable-foo.php
  tests/phpunit/tests/test-model.php
Labels: enhancement

#1245 PHPStan for WP 6.2
  include/links-domain.php
  include/model.php
  include/rest-request.php
  phpstan-baseline.neon
  phpstan.neon.dist
Labels: phpstan

#1248 Add am, arg and es_DO languages
  settings/languages.php
Labels: enhancement

#1253 Fix the display of PLL_Language::$term_props in the health site.
  modules/site-health/admin-site-health.php
  tests/phpunit/tests/test-admin-site-health.php
Labels: bug, Site Health

#1247 Fix languages not displayed if transient is an empty array
  include/model.php
Labels: bug

#1256 Skip widgets REST render for WordPress lower than 5.9.
  tests/phpunit/tests/test-widget-nav-menu.php
Labels: phpunit tests

#1249 Make `term_language` taxonomy optional when creating languages.
  include/language-factory.php
  include/language.php
  include/model.php
  tests/phpunit/tests/test-create-delete-languages.php
Labels: phpstan

#1255 Bump min WP version to 5.8
  .travis.yml
  phpcs.xml.dist
  polylang.php
  readme.md
  readme.txt
Labels: enhancement

#1243 Remove PLL_Block_Editor_Filter_Preload_Paths.
  admin/admin-block-editor.php
  admin/block-editor-filter-preload-paths.php
  tests/phpunit/tests/test-admin-block-editor-test.php
  tests/phpunit/tests/test-block-editor-preload-paths.php
Labels: enhancement

#1187 Use custom query to search for untranslated posts.
  include/translated-post.php
  tests/phpunit/tests/test-ajax-filters-post.php
Labels: bug

#1259 Backward compatibility for `WP_Block_Editor_Context::$name` prop.
  admin/admin-block-editor.php
Labels: bug

#1260 Don't remove legacy strings translations at upgrade
  install/upgrade.php
  uninstall.php
Labels: enhancement

#1258 Fix infinite loop in wizard 🧙‍♂️
  include/model.php
  include/translatable-object.php
  modules/wizard/wizard.php
  phpstan-baseline.neon
Labels: wizard

#1244 Reorder language terms by slug with language taxonomy first
  admin/admin-model.php
  include/crud-terms.php
  include/model.php
  tests/phpunit/tests/test-create-delete-languages.php
Labels: bug

#1262 Fix issues reported by phpstan-wordpress 1.2.0
  admin/admin-classic-editor.php
  frontend/frontend-auto-translate.php
  include/model.php
Labels: phpstan

#1265 Fix PHPStan error
  admin/admin-base.php
  phpstan-baseline.neon
Labels: phpstan

#1264 Avoid a fatal error if the WPML registered string option is corrupted
  modules/wpml/wpml-compat.php
Labels: WPML API

#1263 Load settings views in an action
  settings/settings.php
  settings/view-languages.php
Labels: enhancement

#1266 Add new WPML API filters
  modules/wpml/wpml-api.php
  tests/phpunit/tests/test-wpml.php
Labels: WPML API
