Repository polylang/polylang, pull requests merged in 2023-03, with the labels that each got.

#1226 Remove wpcom_vip_get_page_by_title()
  include/functions.php
Labels: WP 6.2

#1229 Add a new method query_objects_with_no_lang().
  include/translatable-object.php
Labels: enhancement

#1211 Don't cache incomplete languages list
  admin/admin-base.php
  frontend/frontend.php
  include/model.php
  include/rest-request.php
  tests/phpunit/includes/testcase-trait.php
  tests/phpunit/tests/test-create-delete-languages.php
Labels: enhancement

#1232 Simplify code to get objects with no language
  include/model.php
  include/translatable-object-with-types-trait.php
  include/translatable-object.php
Labels: enhancement

#1233 Adds a test to check if there is a translation group after deleting a term translation.
  include/translated-term.php
  tests/phpunit/tests/test-translated-term.php
Labels: bug

#1228 New `$is_default` property in `PLL_Language`.
  admin/admin-filters.php
  admin/admin-model.php
  frontend/choose-lang.php
  frontend/frontend-filters.php
  frontend/frontend-nav-menu.php
  include/filters.php
  include/language-factory.php
  include/language.php
  include/links-default.php
  include/links-directory.php
  include/links-permalinks.php
  include/links-subdomain.php
  include/model.php
  include/nav-menu.php
  modules/wizard/view-wizard-step-home-page.php
  modules/wizard/view-wizard-step-languages.php
  modules/wizard/view-wizard-step-untranslated-contents.php
  modules/wpml/wpml-compat.php
  phpstan-baseline.neon
  settings/settings-url.php
  settings/table-languages.php
  tests/phpunit/tests/test-create-delete-languages.php
Labels: enhancement

#1235 Add annotation for PHP 8.1+
  include/translatable-objects.php
Labels: bug

#1234 New parameter `hide_default` in `PLL_Model::get_languages_list()`.
  include/links-directory.php
  include/links-subdomain.php
  include/model.php
  modules/sitemaps/sitemaps.php
  tests/phpunit/tests/test-model.php
Labels: enhancement

#1210 Deprecate language list filters
  include/model.php
Labels: enhancement, Status: ready to merge

#1240 Move doing_it_wrong_trigger_error related code in a trait.
  tests/phpunit/includes/bootstrap.php
  tests/phpunit/includes/doing-it-wrong-trait.php
  tests/phpunit/includes/testcase-trait.php
Labels: phpunit tests

#1239 Fixes PLL_Language::get_prop()
  include/language-deprecated.php
  include/language.php
  tests/phpunit/includes/bootstrap.php
  tests/phpunit/includes/polyfills.php
  tests/phpunit/tests/test-language.php
Labels: bug
