Repository polylang/polylang, pull requests merged in 2023-02, with the labels that each got.

#1207 Fix all new issues reported by PHPStan
  admin/admin-filters-media.php
  admin/admin-filters-post.php
  admin/admin-filters-term.php
  admin/admin-model.php
  frontend/choose-lang-content.php
  frontend/choose-lang.php
  frontend/frontend-filters-search.php
  frontend/frontend-filters.php
  frontend/frontend-links.php
  frontend/frontend-static-pages.php
  include/crud-posts.php
  include/language-factory.php
  include/language.php
  include/links.php
  include/model.php
  include/static-pages.php
  include/translatable-objects.php
  include/translated-object.php
  modules/site-health/admin-site-health.php
  modules/sync/sync-tax.php
  modules/wizard/wizard.php
  modules/wpml/wpml-api.php
  phpstan-baseline.neon
  settings/settings-url.php
  settings/settings.php
Labels: coding standards, phpstan

#1213 Get ready for WP 6.2
  admin/admin-model.php
  frontend/frontend-filters-search.php
  tests/phpunit/tests/test-copied-functions.php
Labels: WP 6.2

#1219 Fix message for deprecated property
  include/language.php
Labels: enhancement

#1217 Check mu plugin files are readable.
  admin/admin-model.php
  include/class-polylang.php
  include/language.php
  modules/wpml/wpml-config.php
Labels: bug

#1209 Removes mo_id from PLL_Language
  admin/admin-model.php
  include/language-factory.php
  include/language.php
  include/mo.php
  install/upgrade.php
  phpstan-baseline.neon
  tests/phpunit/tests/test-create-delete-languages.php
  tests/phpunit/tests/test-install.php
  uninstall.php
Labels: enhancement

#1202 Remove PLL_Language dynamic property in PLL_Walker_Dropdown
  include/language.php
  include/links-default.php
  include/links-permalinks.php
  include/model.php
  include/switcher.php
  include/walker-dropdown.php
  include/walker-list.php
  include/walker.php
  modules/site-health/admin-site-health.php
  phpstan-baseline.neon
Labels: enhancement

#1224 Don't set update plugins transient to null
  include/license.php
Labels: compatibility
