Repository polylang/polylang, pull requests merged in 2024-10, with the labels that each got.

#1551 Fix issue reported by PHPStan (`rest_route` as an array)
  include/class-polylang.php
Labels: phpstan

#1552 New hook `pll_upgrade`.
  install/upgrade.php
Labels: enhancement

#1550 Don't use textdomains until `after_setup_theme`
  admin/admin-base.php
  include/translated-post.php
  modules/wpml/wpml-compat.php
Labels: WP 6.7

#1557 Don't use textdomains until `after_setup_theme` in 3.7 code
  include/Options/Business/Sync.php
  modules/sync/settings-sync.php
Labels: WP 6.7

#1526 Fix empty notice displayed if plugin upgrade notice is set but empty
  admin/admin.php
Labels: bug

#1561 Introduce get_data_from_new_media_translation_request()
  admin/admin-filters-media.php
  admin/admin-filters-post-base.php
  admin/admin-links.php
Labels: enhancement

#1562 Use parallel processing and cache for PHPCS
  phpcs.xml.dist
Labels: coding standards

#1553 Avoid a phpcs:ignore and reformat option_sticky_posts()
  frontend/frontend-filters.php
Labels: enhancement, coding standards

#1559 Fix (most of) PHPStan errors in WPML compatibility code
  modules/wpml/wpml-api.php
  modules/wpml/wpml-compat.php
  modules/wpml/wpml-legacy-api.php
  phpstan-baseline.neon
Labels: phpstan

#1563 Update plugin updater to version 1.9.4
  install/plugin-updater.php
Labels: bug

#1565 Exclude `PLL_Plugin_Updater` from Typos and Rector tools
  .typos.toml
  rector.php
Labels: doc

#1556 Remove phpcs:ignore WordPress.DB.PreparedSQL in Model\Languages
  include/Model/Languages.php
Labels: enhancement, coding standards

#1558 Reformat SQL queries using `PLL_Db_Tools`
  include/db-tools.php
  include/translatable-object-with-types-trait.php
  include/translatable-object.php
  include/translated-post.php
  include/translated-term.php
  tests/phpunit/tests/test-db-tools.php
Labels: enhancement, coding standards

#1564 Fix "Language is defined from the content" front page
  include/translated-post.php
  tests/phpunit/tests/test-choose-lang-content.php
Labels: bug
