Repository polylang/polylang, pull requests merged in 2024-04, with the labels that each got.

#1457 Remove rewrite when registering the language taxonomy
  include/links-directory.php
  include/translated-post.php
  tests/phpunit/tests/test-single-language.php
Labels: bug, validated

#1459 Fix search block filter
  frontend/frontend-filters-search.php
  tests/phpunit/tests/test-search-form.php
Labels: bug

#1458 Restore current language management in multisite.
  include/cache.php
  include/translated-post.php
  include/translated-term.php
  tests/phpunit/includes/testcase-multisites.php
  tests/phpunit/tests/test-switch-blog-custom-code.php
Labels: bug, validated, multisite

#1464 Run typos on PR, commit and dispatch.
  .github/workflows/typos.yml
  readme.txt
Labels: tools

#1423 Translate the content of the widget custom html
  admin/admin-strings.php
Labels: enhancement

#1469 Fix new issues reported by phpstan
  admin/admin-base.php
  include/translate-option.php
  phpstan-baseline.neon
  phpstan.neon.dist
Labels: phpstan

#1470 Require PHP 7.2
  .github/workflows/integration-and-unit-tests.yml
  composer.json
  phpcs.xml.dist
  polylang.php
  readme.txt
Labels: enhancement

#1471 Explicit implicitly nullable parameter
  include/model.php
Labels: php 8.4
