Repository polylang/polylang, pull requests merged in 2024-09, with the labels that each got.

#1535 Don't disable phpcs
  admin/admin-filters-columns.php
Labels: coding standards

#1529 Adds an event when the lang has been changed on `post_lang_choice`.
  include/switcher.php
  include/walker-dropdown.php
  include/walker.php
  js/src/classic-editor.js
Labels: enhancement

#1538 Remove remaining `phpcs:disable`
  include/Model/Languages.php
  integrations/wp-importer/wp-import.php
  js/src/classic-editor.js
Labels: coding standards

#1532 Harmonize context checks in `PLL_Admin_Sync`
  admin/admin-links.php
  modules/sync/admin-sync.php
  tests/phpunit/tests/test-media.php
  tests/phpunit/tests/test-sync.php
  tests/phpunit/tests/test-wpml-config.php
Labels: enhancement

#1533 Filter `/wp-block-editor/v1/navigation-fallback` by language when applicable.
  include/filter-rest-routes.php
Labels: bug, block editor

#1546 Allow numbers in language code
  include/Model/Languages.php
  include/Options/Business/Default_Lang.php
  include/Options/Business/Domains.php
  include/Options/Business/Nav_Menus.php
  modules/REST/V1/Languages.php
  tests/phpunit/tests/test-option-schema.php
Labels: enhancement
