Repository polylang/polylang, pull requests merged in 2024-07, with the labels that each got.

#1502 Fix Polylang's options in Site Health
  include/Options/Options.php
Labels: bug, Site Health

#1508 `prepare_raw_data()` returns options instead of an empty array
  settings/settings-module.php
Labels: enhancement, Options

#1503 Make `PLL_Admin_Model`'s methods available in all contexts
  admin/admin-model.php
  include/Model/Languages.php
  include/Model/Post_Types.php
  include/Model/Taxonomies.php
  include/model.php
  include/translatable-object.php
  include/translated-object.php
  include/translated-post.php
  include/translated-term.php
  phpstan-baseline.neon
  phpstan.neon.dist
  polylang.php
  tests/phpunit/includes/doing-it-wrong-trait.php
  tests/phpunit/tests/test-model.php
  tests/phpunit/tests/test-translated-post.php
  tests/phpunit/tests/test-translated-term.php
Labels: enhancement

#1512 Adds a condition not to update page_on_front and page_for_posts options
  include/static-pages.php
  tests/phpunit/tests/test-static-pages.php
  tests/phpunit/tests/test-translate-page-for-posts.php
Labels: bug

#1514 Fix tests
  tests/phpunit/includes/testcase-trait.php
  tests/phpunit/tests/test-default-term.php
  tests/phpunit/tests/test-switch-blog-query.php
  tests/phpunit/tests/test-sync.php
Labels: phpunit tests

#1500 Adds wrapper for `wp_insert_term` and `wp_update_term`.
  include/api.php
  include/translated-term.php
  tests/phpunit/tests/test-api.php
Labels: enhancement
