Repository polylang/polylang, pull requests merged in 2024-06, with the labels that each got.

#1486 Replace all ocurrences of esc_url_raw() by sanitize_url()
  admin/admin-model.php
  include/functions.php
  include/language-factory.php
  include/language.php
  modules/wizard/view-wizard-step-media.php
  modules/wizard/wizard.php
  settings/settings-url.php
Labels: enhancement

#1485 Tests about option schemas
  tests/phpunit/includes/options-trait.php
  tests/phpunit/tests/test-olt-manager.php
  tests/phpunit/tests/test-option-schema.php
Labels: phpunit tests

#1489 Fix a regression in usage of the `pll_flag` filter
  include/language.php
Labels: bug

#1492 Rename files to match the class names
  include/Options/Abstract_Option.php
  include/Options/Business/Abstract_Object_Types.php
  include/Options/Business/Browser.php
  include/Options/Business/Domains.php
  include/Options/Business/First_Activation.php
  include/Options/Business/Force_Lang.php
  include/Options/Business/Hide_Default.php
  include/Options/Business/Language_Slug.php
  include/Options/Business/Language_Taxonomies.php
  include/Options/Business/Media_Support.php
  include/Options/Business/Nav_Menus.php
  include/Options/Business/Post_Types.php
  include/Options/Business/Previous_Version.php
  include/Options/Business/Redirect_Lang.php
  include/Options/Business/Rewrite.php
  include/Options/Business/Sync.php
  include/Options/Business/Taxonomies.php
  include/Options/Business/Version.php
  include/Options/Options.php
  include/Options/Primitive/Abstract_Boolean.php
  include/Options/Primitive/Abstract_List.php
  include/Options/Primitive/Abstract_String.php
  include/Options/Registry.php
Labels: enhancement

#1493 Fix the latest phpstan errors
  frontend/frontend.php
  include/translatable-objects.php
  phpstan-baseline.neon
Labels: phpstan

#1491 Rector-ize up to PHP 7.2
  admin/admin-default-term.php
  admin/admin-filters-columns.php
  admin/admin-notices.php
  admin/admin-strings.php
  admin/view-translations-post.php
  admin/view-translations-term.php
  composer.json
  frontend/accept-language.php
  frontend/canonical.php
  frontend/choose-lang-content.php
  frontend/frontend-static-pages.php
  frontend/frontend.php
  include/api.php
  include/cache.php
  include/crud-terms.php
  include/db-tools.php
  include/language-deprecated.php
  include/language.php
  include/links-subdomain.php
  include/switcher.php
  include/translate-option.php
  include/translated-object.php
  include/walker.php
  install/plugin-updater.php
  install/t15s.php
  integrations/wpseo/wpseo.php
  modules/sitemaps/multilingual-sitemaps-provider.php
  modules/sync/sync.php
  modules/wpml/wpml-api.php
  modules/wpml/wpml-config.php
  phpcs.xml.dist
  rector.php
  settings/settings-url.php
  tests/phpunit/includes/mocks-trait.php
  tests/phpunit/includes/polyfill-testcase.php
  tests/phpunit/tests/test-choose-lang-content.php
  tests/phpunit/tests/test-choose-lang-domain.php
  tests/phpunit/tests/test-links-domain.php
  tests/phpunit/tests/test-static-pages.php
Labels: tools

#1495 Fix issues reported by Rector
  include/Options/Business/Domains.php
  include/Options/Options.php
  include/Options/Registry.php
  tests/phpunit/tests/test-admin-filters-term.php
  tests/phpunit/tests/test-links-domain.php
  tests/phpunit/tests/test-option-schema.php
Labels: enhancement, coding standards

#1497 Allow to pass an array as context to icl_register_string()
  modules/wpml/wpml-compat.php
  tests/phpunit/tests/test-wpml.php
Labels: bug, WPML API

#1496 Fix admin bar search menu in WP 6.6
  frontend/frontend-filters-search.php
Labels: validated, WP 6.6

#1490 Avoid term duplication when same name and empty slug.
  include/crud-terms.php
  include/term-slug.php
  phpstan.neon.dist
  tests/phpunit/tests/test-admin-filters-term.php
  tests/phpunit/tests/test-copied-functions.php
Labels: bug

#1498 Fix tests on multisite
  include/Options/Business/Default_Lang.php
  include/Options/Options.php
  include/Options/Registry.php
  include/links-domain.php
  tests/phpunit/includes/testcase-multisites.php
  tests/phpunit/includes/testcase-trait.php
  tests/phpunit/includes/testcase.php
  tests/phpunit/tests/test-option-schema.php
  tests/phpunit/tests/test-switch-blog-rewrite-rules.php
Labels: bug, phpunit tests
