Repository polylang/polylang, pull requests merged in 2024-03, with the labels that each got.

#1432 Don't print the setting form of an inactive module
  settings/settings-module.php
Labels: enhancement

#1406 Allow setcookie httponly args to be filtered
  include/cookie.php
Labels: enhancement

#1436 Update post.js – fix #1435
  js/src/post.js
Labels: bug

#1442 Uppercase 'DeepL Translate'
  modules/machine-translation/settings-preview-machine-translation.php
Labels: enhancement

#1441 Require WP 6.2
  .github/workflows/integration-and-unit-tests.yml
  phpcs.xml.dist
  polylang.php
  readme.md
  readme.txt
  tests/phpunit/includes/bootstrap.php
  tests/phpunit/includes/polyfills.php
  tests/phpunit/tests/plugins/test-jetpack.php
Labels: enhancement

#1439 Fix possible warning in view-translations-post.php
  admin/view-translations-post.php
Labels: bug

#1434 Adds sub-levels attribute keys support in wpml config
  modules/wpml/wpml-config.php
  tests/phpunit/data/wpml-config.xml
  tests/phpunit/tests/test-wpml-config.php
Labels: enhancement, WPML API

#1444 Protects access to innerHTML property when the HTML id doesn't exist
  js/src/term.js
Labels: bug, validated

#1433 Add Typos to CI
  .github/workflows/typos.yml
  .typos.toml
  admin/admin-model.php
  include/language-factory.php
  include/language.php
  settings/view-tab-lang.php
  tests/bin/install-plugins.sh
Labels: tools

#1404 Wilcards in `PLL_WPML_Config` and `PLL_Translate_Option`
  include/format-util.php
  include/translate-option.php
  modules/wpml/wpml-config.php
  phpstan-baseline.neon
  tests/phpunit/data/wpml-config.xml
  tests/phpunit/tests/test-translate-option.php
  tests/phpunit/tests/test-wpml-config.php
Labels: enhancement

#1450 WPCS 3.1
  include/model.php
  include/translated-post.php
  modules/wizard/wizard.php
  phpcs.xml.dist
Labels: coding standards

#1454 Make add_all_meta_actions() and remove_all_meta_actions() method accessible
  modules/sync/sync-metas.php
Labels: bug, compatibility
