Repository polylang/polylang, pull requests merged in 2024-01, with the labels that each got.

#1402 Support JSON encoding for metas in `wpml-config.xml`
  modules/wpml/wpml-config.php
  tests/phpunit/data/wpml-config.xml
  tests/phpunit/tests/test-wpml-config.php
Labels: WPML API

#1403 Use a template and generics to document `PLL_Cache`
  frontend/frontend-filters-links.php
  frontend/frontend-filters-widgets.php
  frontend/frontend-links.php
  include/cache.php
  include/model.php
  include/translate-option.php
  phpstan-baseline.neon
  tests/phpunit/tests/test-widgets-filter.php
Labels: enhancement, phpstan

#1409 Cast `pll_get_post_types` and `pll_get_taxonomies` returned values.
  include/translated-post.php
  include/translated-term.php
Labels: enhancement

#1408 Migrate some tests to use the new context init and factory
  tests/phpunit/includes/context/context-base.php
  tests/phpunit/includes/context/context-frontend.php
  tests/phpunit/includes/context/context-rest.php
  tests/phpunit/tests/test-admin-filters.php
  tests/phpunit/tests/test-auto-translate.php
  tests/phpunit/tests/test-columns.php
  tests/phpunit/tests/test-create-delete-languages.php
  tests/phpunit/tests/test-crud-posts.php
  tests/phpunit/tests/test-hreflang.php
  tests/phpunit/tests/test-rest-request.php
  tests/phpunit/tests/test-slugs.php
Labels: phpunit tests

#1412 Use _prime_post_caches() to cache the pages for posts
  frontend/frontend-static-pages.php
  phpstan.neon.dist
Labels: Performance

#1411 Fix usages of `add_settings_error()`
  settings/settings-licenses.php
  settings/settings-module.php
  settings/settings-url.php
  settings/settings.php
  settings/table-string.php
Labels: bug

#1414 Don't minify files in tests folder
  webpack.config.js
Labels: tools

#1405 Fix typos
  admin/admin-base.php
  admin/admin-filters-columns.php
  admin/admin-filters-term.php
  admin/admin-model.php
  changelog.txt
  composer.json
  include/crud-posts.php
  include/language.php
  include/model.php
  include/rest-request.php
  include/translatable-object.php
  include/translated-post.php
  include/translated-term.php
  install/install-base.php
  install/plugin-updater.php
  integrations/wp-offload-media/as3cf.php
  integrations/wpseo/wpseo.php
  js/src/admin.js
  js/src/block-editor.js
  js/src/classic-editor.js
  js/src/lib/confirmation-modal.js
  js/src/lib/filter-path-middleware.js
  js/src/nav-menu.js
  js/src/post.js
  modules/site-health/admin-site-health.php
  modules/sitemaps/multilingual-sitemaps-provider.php
  modules/sync/admin-sync.php
  modules/sync/sync-metas.php
  modules/sync/sync-post-metas.php
  modules/sync/sync-tax.php
  modules/sync/sync.php
  modules/wizard/js/languages-step.js
  modules/wizard/wizard.php
  modules/wpml/wpml-api.php
  modules/wpml/wpml-legacy-api.php
  phpunit.xml
  settings/settings.php
  settings/table-string.php
  tests/phpunit/data/translatable-foo.php
  tests/phpunit/includes/handle-wp-redirect-trait.php
  tests/phpunit/includes/testcase-trait.php
  tests/phpunit/includes/testcase-translated-object.php
  tests/phpunit/tests/test-accept-language.php
  tests/phpunit/tests/test-admin-notices.php
  tests/phpunit/tests/test-canonical.php
  tests/phpunit/tests/test-choose-lang.php
  tests/phpunit/tests/test-create-delete-languages.php
  tests/phpunit/tests/test-crud-posts.php
  tests/phpunit/tests/test-languages-list.php
  tests/phpunit/tests/test-query.php
  tests/phpunit/tests/test-search-form.php
  tests/phpunit/tests/test-widgets-filter.php
  tests/phpunit/tests/test-wpml-config.php
  tests/phpunit/tests/test-wpml.php
  uninstall.php
Labels: doc
