Repository polylang/polylang, pull requests merged in 2024-05, with the labels that each got.

#1451 Create classes to manage options as objects.
  include/options/abstract-option.php
  include/options/business/abstract-object-types.php
  include/options/business/browser.php
  include/options/business/domains.php
  include/options/business/hide-default.php
  include/options/business/language-slug.php
  include/options/business/language-taxonomies.php
  include/options/business/nav-menus.php
  include/options/business/post-types.php
  include/options/business/sync.php
  include/options/business/taxonomies.php
  include/options/options.php
  include/options/primitive/boolean.php
  include/options/primitive/choice.php
  include/options/primitive/integer.php
  include/options/primitive/list-type.php
  include/options/primitive/string-type.php
Labels: enhancement

#1480 PHPStan 1.11.0 + WP stubs 6.5.3
  admin/admin-filters-widgets-options.php
  include/filters-widgets-options.php
  include/widget-languages.php
  phpstan.neon.dist
Labels: phpstan

#1395 Fix translations not loaded when the language is set from the content
  include/olt-manager.php
  tests/phpunit/tests/test-olt-manager.php
Labels: bug, validated

#1359 Register the language taxonomy only once
  include/translatable-object.php
  include/translated-object.php
  include/translated-post.php
  tests/features/bootstrap/BrowserPreferredLanguageContext.php
  tests/phpunit/includes/testcase-canonical.php
  tests/phpunit/tests/test-admin-filters-post.php
  tests/phpunit/tests/test-ajax-filters-post.php
  tests/phpunit/tests/test-choose-lang-content.php
  tests/phpunit/tests/test-choose-lang-domain.php
  tests/phpunit/tests/test-choose-lang.php
  tests/phpunit/tests/test-filters-links.php
  tests/phpunit/tests/test-filters.php
  tests/phpunit/tests/test-model.php
  tests/phpunit/tests/test-query.php
  tests/phpunit/tests/test-search-form.php
  tests/phpunit/tests/test-single-language.php
  tests/phpunit/tests/test-sitemaps.php
  tests/phpunit/tests/test-static-pages.php
  tests/phpunit/tests/test-switcher.php
  tests/phpunit/tests/test-wpml.php
Labels: enhancement, Performance

#1484 Don't fire `change_locale` too soon
  include/olt-manager.php
Labels: bug
