Repository polylang/polylang, pull requests merged in 2024-02, with the labels that each got.

#1415 Fix wrong post types and taxonomies cached during a switch_blog()
  include/cache.php
  tests/phpunit/tests/test-switch-blog-translatable-objects.php
Labels: bug, multisite

#1418 Don't set post tags with names. Use term ids instead
  include/crud-posts.php
  tests/phpunit/tests/test-crud-posts.php
Labels: bug, validated

#1425 Fixes PHPStan WP_Query::$query undefined error
  frontend/canonical.php
  phpstan.neon.dist
Labels: phpstan

#1424 Replace settings error slug with polylang
  settings/settings-licenses.php
  settings/settings-module.php
  settings/settings-url.php
  settings/settings.php
  settings/table-string.php
Labels: bug

#1428 Fix DB failure in PHPUnit CI.
  .github/workflows/integration-and-unit-tests.yml
Labels: tools

#1426 Strings review
  modules/machine-translation/settings-preview-machine-translation.php
Labels: enhancement

#1427 Trigger a JS hook when settings are saved
  js/src/admin.js
  settings/settings.php
Labels: enhancement

#1429 Install plugins and themes correctly in CI.
  .github/workflows/integration-and-unit-tests.yml
  tests/bin/install-plugins.sh
Labels: tools

#1430 Adds an add_settings_error() wrapper and uses it
  include/functions.php
  settings/settings-licenses.php
  settings/settings-module.php
  settings/settings-url.php
  settings/settings.php
  settings/table-string.php
Labels: bug
