Repository polylang/polylang, pull requests merged in 2025-05, with the labels that each got.

#1660 Elvis now
  frontend/choose-lang.php
  frontend/frontend-auto-translate.php
  modules/sync/sync-post-metas.php
Labels: enhancement

#1663 Update `get_calendar()` hash
  tests/phpunit/tests/test-copied-functions.php
Labels: phpunit tests, WP 6.9

#1666 Reformat Twenty Twenty Four tests
  tests/phpunit/tests/themes/test-twenty-fourteen.php
Labels: phpunit tests, coding standards

#1664 Allow to customize the name of the translation term
  include/translated-object.php
Labels: enhancement

#1671 Avoids syncing term parent on term creation if parent term isn't translated.
  modules/sync/sync.php
  tests/phpunit/tests/test-sync.php
Labels: bug

#1674 Fix JS TypeError in media library.
  admin/admin-base.php
  js/src/media.js
  js/src/post.js
  tests/phpunit/tests/test-admin-assets.php
Labels: bug

#1672 Prevent duplicate values in list-type options
  include/Options/Primitive/Abstract_List.php
  tests/phpunit/data/translatable-foo.php
  tests/phpunit/data/translatable.php
  tests/phpunit/tests/Options/Abstract_List/test-Prepare.php
  tests/phpunit/tests/test-model.php
Labels: bug, Options

#1668 Remove useless `$post_type` param
  admin/admin-links.php
  modules/sync/admin-sync.php
  tests/phpunit/tests/test-sync.php
Labels: enhancement
