Repository polylang/polylang, pull requests merged in 2025-01, with the labels that each got.

#1605 Fix attachment page redirected to 404
  frontend/canonical.php
Labels: bug, validated, WP 6.4

#1607 Fix typo in JS comment
  js/src/admin.js
Labels: doc

#1571 Restrict option sanitization to the relevant string
  include/translate-option.php
  phpstan-baseline.neon
  settings/table-string.php
  tests/phpunit/tests/test-translate-option.php
Labels: bug

#1608 Loads strings translations with the media's target language on media creation.
  include/translated-post.php
  tests/phpunit/tests/test-admin-filters-post.php
Labels: enhancement, validated

#1617 Do not relate an object to a term if the term does not exist.
  include/crud-posts.php
  tests/phpunit/tests/test-crud-posts.php
Labels: bug

#1610 Make sure language slugs in the `nav_menus` option correspond to existing languages
  include/Options/Abstract_Option.php
  include/Options/Business/Domains.php
  include/Options/Business/Nav_Menus.php
  tests/phpunit/tests/Options/Options/test-Set.php
  tests/phpunit/tests/test-nav-menus.php
Labels: bug, enhancement, Options

#1612 Handle breaking changes in jQuery 4's AJAX prefilter
  admin/admin-base.php
  js/src/admin.js
  js/src/lib/ajax-filter/index.js
  js/src/settings.js
  modules/wizard/wizard.php
  settings/settings.php
Labels: bug, jQuery update, validated, WP 6.8

#1618 Ignore coverage folder from the webpack build process and distributing process
  .distignore
  webpack.config.js
Labels: tools
