Repository polylang/polylang, pull requests merged in 2025-03, with the labels that each got.

#1632 Review strings and comments for translators
  include/Options/Business/Browser.php
  include/Options/Business/Hide_Default.php
  include/Options/Business/Media_Support.php
  include/Options/Business/Redirect_Lang.php
  include/Options/Business/Rewrite.php
  modules/REST/V1/Languages.php
Labels: enhancement

#1637 Update import of strings translations with WP Importer.
  integrations/wp-importer/wp-import.php
  tests/phpunit/data/test-import.xml
  tests/phpunit/tests/plugins/test-wp-importer.php
Labels: bug, WP Importer

#1634 Fix test failing due to `get_calendar()`
  include/widget-calendar.php
  tests/phpunit/tests/test-copied-functions.php
Labels: WP 6.8

#1639 Avoid double escape
  modules/site-health/admin-site-health.php
Labels: Site Health

#1641 Fix widget block wrongly added to string translation
  admin/admin-strings.php
Labels: bug

#1638 Fix a conflict with WooCommerce Price Based on Country
  frontend/frontend-auto-translate.php
  tests/phpunit/tests/test-auto-translate.php
Labels: compatibility

#1644 Avoid fetching `active_sitewide_plugins` on single site installation.
  include/Options/Options.php
  tests/phpunit/tests/Performances/test-Single_Site.php
Labels: enhancement

#1645 Fix integrations' singleton
  integrations/integrations.php
Labels: bug, Performance
