Repository polylang/polylang, pull requests merged in 2025-07, with the labels that each got.

#1695 Fixes typo in comment.
  include/Model/Languages.php
Labels: doc

#1691 Prevent warnings in `PLL_Canonical::get_queried_term_id()`.
  frontend/canonical.php
Labels: bug

#1699 Prevent calling `PLL_Settings::handle_actions()` with empty action.
  settings/settings.php
Labels: bug

#1702 Updates DeepL supported languages.
  settings/languages.php
Labels: enhancement

#1705 Adds get_post_meta() and get_term_meta() $single parameter
  tests/phpunit/tests/test-sync.php
Labels: coding standards
