Repository polylang/polylang, pull requests merged in 2025-02, with the labels that each got.

#1543 adding the language code in the language section
  modules/site-health/admin-site-health.php
Labels: enhancement, Site Health

#1623 Remove title attribute in `get_calendar()`
  include/widget-calendar.php
  tests/phpunit/tests/test-copied-functions.php
Labels: accessibility, WP 6.8

#1624 Add `aria-current` attribute in language switcher
  include/walker-list.php
Labels: enhancement, accessibility

#1627 Fix `wp_kses()` tag attributes
  include/functions.php
Labels: bug

#1626 Adds an event when the lang has been changed on term_lang_choice. #1529
  js/src/term.js
Labels: enhancement

#1628 Improve some descriptions
  include/Options/Business/Rewrite.php
  modules/REST/V1/Languages.php
  modules/site-health/admin-site-health.php
  settings/settings-url.php
Labels: enhancement

#1622 Use `wp_add_inline_script()` to add our cookie script.
  integrations/cache/cache-compat.php
Labels: enhancement
