Repository polylang/polylang, pull requests merged in 2025-09, with the labels that each got.

#1601 Use determine_locale() instead of get_locale() to get HTML language attributes correctly on the log in page
  include/filters.php
  tests/phpunit/tests/test-filters.php
Labels: bug

#1718 Prevent a translations group extra update
  include/translated-object.php
  tests/phpunit/tests/test-translated-post.php
  tests/phpunit/tests/test-translated-term.php
Labels: enhancement

#1720 Create a GitHub workflow to add "needs triage" label to new issues.
  .github/workflows/new-issue-workflow.yml
Labels: tools

#1719 Improve error management for in `Model\Languages`.
  include/Model/Languages.php
Labels: enhancement

#1725 Only add translatable content IDs to AJAX filter data.
  admin/admin-base.php
Labels: bug

#1704 Rework `PLL_Install`
  .github/workflows/static-analysis.yml
  composer.json
  include/class-polylang.php
  include/constant-functions.php
  include/functions.php
  install/abstract-activable.php
  install/abstract-activate.php
  install/abstract-deactivate.php
  install/activate.php
  install/deactivate.php
  install/install-base.php
  install/install.php
  install/usable.php
  phpcs-phpcompatibility-56.xml.dist
  polylang.php
  tests/phpunit/tests/test-install.php
Labels: enhancement

#1698 Hide Polylang's admin bar menu on content edit screens
  admin/admin-base.php
  tests/phpunit/includes/testcase-trait.php
  tests/phpunit/tests/test-admin.php
Labels: enhancement

#1727 [Capabilities] String translations screen
  admin/admin-base.php
  include/Capabilities/Capabilities.php
  include/Model/Languages.php
  include/Model/Languages_Proxies.php
  include/Model/Languages_Proxy_Interface.php
  include/base.php
  settings/settings.php
  settings/table-string.php
  settings/view-tab-strings.php
  tests/phpunit/tests/test-settings-list-tables.php
Labels: enhancement
